### PR TITLE
Adding docker and podman commands to Bash language

### PR DESCRIPTION
**Pull request by AmebaBrain**
Added following commands to the `bash` language
- `docker`
- `docker-compose`
- `podman`
- `podman-compose`

According to guidelines minified file is not touched.

### CODE REVIEW

**Comment by RunDevelopment** [comment]
Thank you for the PR @AmebaBrain!

> According to guidelines minified file is not touched.

When changing a language, the minified files are supposed to be updated. Seems like our docs need some clarification. Where did you read this?

**Comment by AmebaBrain** [comment]
@RunDevelopment 

2nd point in Contribute to Prism! section of readme says
> Limit your changes to the unminified files in the `components/` folder. `prism.js` and all minified files are also generated automatically by our build system.

Anyway, I've pushed the changes to the minified file as well. Because I did this from a new Windows based laptop please check whether line ending in a minified file is ok. If not, I will re-execute `npm run build` from Linux based machine day after tommorow.

**Comment by RunDevelopment** [comment]
> 2nd point in Contribute to Prism! section of readme says

Good point. I'll clarify this tomorrow.

**Review by RunDevelopment — APPROVED** [review]

**Comment by RunDevelopment** [comment]
Thank you for contributing @AmebaBrain!

**Pull request merged**
