### PR TITLE
Rust: Improved punctuation and operators

### PR DESCRIPTION
**Pull request by RunDevelopment**
This PR improves Rust's punctuation as discussed [here](https://github.com/PrismJS/prism/issues/1133#issuecomment-477083436).

Edit:
It now also adds support for the missing [`..=`](https://doc.rust-lang.org/std/ops/struct.RangeToInclusive.html) and [`?`](https://doc.rust-lang.org/edition-guide/rust-2018/error-handling-and-panics/the-question-mark-operator-for-easier-error-handling.html) syntax.

### CODE REVIEW

**Comment by dsvensson** [comment]
List of operators:
https://doc.rust-lang.org/book/appendix-02-operators.html

**Comment by dsvensson** [comment]
Verified.. thanks!

**Comment by dsvensson** [comment]
Any thoughts on when this will be released?

**Comment by RunDevelopment** [comment]
This will be released as part of the next version of Prism (v1.17). We don't have a date for that release yet.

If you need this feature, you can go to the [download page](https://prismjs.com/download.html) and get Prism from there. This version of Prism includes all the new features we added since the last release.

**Pull request merged**
