### PR TITLE
Website: Improved readability

### LINKED ISSUE #3175: prismjs.com has poor readability
That background image provides a very poor contrast.

image

image

### PR DESCRIPTION
**Pull request by RunDevelopment**
Fixes #3175.

image

image

### CODE REVIEW

**Comment by not-my-profile** [comment]
Thanks, that is definitely better! However I still find the text below the headings to be a bit hard to read. Probably mainly due to the narrow font.

**Comment by RunDevelopment** [comment]
I agree. It's more readable with a larger font size.

image

It's not perfectly readable (it's hard with such a high-contrast background) but I think it's okay-ish.

**Comment by not-my-profile** [comment]
How about something like `linear-gradient( transparent, rgba(0, 0, 0, 0.7) ),url("https://prismjs.com/assets/img/spectrum.png") fixed;`? That is making the background image less distracting by overlaying a transparent gradient?

**Comment by RunDevelopment** [comment]
Very good idea @not-my-profile!

image

**Comment by not-my-profile** [comment]
LGTM!

**Pull request merged**
