### PR TITLE
add advanced graphql changes separate from test changes

### PR DESCRIPTION
**Pull request by JaKXz**
@RunDevelopment ironically after all the discussion about "integration" tests from #2927, I realized the library I'm using that vendors Prism only uses the `.tokenize` method so I'm not able to use plugins anyway 😂 😭 

Here's the PR for just the advanced graphql changes without any major modifications to the test suite :)

Closes #2927

### CODE REVIEW

**Comment by RunDevelopment** [comment]
Sorry for the delay @JaKXz!

> the library I'm using that vendors Prism only uses the `.tokenize` method so I'm not able to use plugins anyway 😂 😭

I'm sorry to hear that. Coincidentally, I just opened an issue for a new hook (#2949) that would solve your problem. But this hook will likely only be added in v2.0.

**Review by RunDevelopment — APPROVED** [review]

**Comment by RunDevelopment** [comment]
I just merged a few PRs that changed a bunch of files. Let me quickly resolve the merge conflict.

**Comment by RunDevelopment** [comment]
@JaKXz Also, you should request your vendor to support the `before-tokenize` and `after-tokenize` hooks. These hooks are necessary for some languages to work properly. Even the new hook I proposed won't change that.

**Comment by JaKXz** [comment]
No worries, thanks for merging! :)

**Pull request merged**
