### PR TITLE
Add file extensions support for major languages

### PR DESCRIPTION
**Pull request by ybiquitous**
This adds aliases for file extensions of some major languages.

- `.coffee` -> `.coffeescript`
- `.md` -> `.markdown`
- `.py` -> `.python`
- `.rb` -> `.ruby`
- `.yml` -> `.yaml`

Such as:

https://github.com/PrismJS/prism/blob/7d084d5f17fa40d3451d46cac605308382c9c499/components/prism-javascript.js#L56

### CODE REVIEW

**Comment by mAAdhaTTah** [comment]
@ybiquitous If you resolve this conflict, I'm good to merge this.

**Comment by ybiquitous** [comment]
@mAAdhaTTah Sorry late reply. 🙇 

I merged right now, please check it when you have a time!

**Comment by RunDevelopment** [comment]
@ybiquitous 
Please also run [gulp](https://github.com/gulpjs/gulp) to generate the minified files.

**Comment by ybiquitous** [comment]
@RunDevelopment Sorry, I pushed now minified version via `gulp`. 👍

**Comment by ybiquitous** [comment]
By the way, what about thinking about auto-minification?

For example, Using [`lint-staged`](https://github.com/okonet/lint-staged) and [`husky`](https://github.com/typicode/husky) can force to generate and commit minified files before commiting *.js files.

```json5
// package.json
{
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged",
    }
  },
  "lint-staged": {
    "*.js": ["gulp", "git add"]
  }
}
```

**Comment by RunDevelopment** [comment]
This certainly is an interesting option.

@mAAdhaTTah What do you think?

**Comment by mAAdhaTTah** [comment]
@RunDevelopment I'm into it. We use that combo @ work without issues. We had also talked about introducing ESLint (#1483); might be worth bundling that together.

**Pull request merged**
