### PR TITLE
Support JSX/TSX class-name with dot

### PR DESCRIPTION
**Pull request by RexSkz**
Support class names like `<Tree.TreeNode.Item>`.

### CODE REVIEW

**Comment by RunDevelopment** [comment]
I really like this change but I also think that we should include a `punctuation` pattern for the dots.

**Comment by RexSkz** [comment]
It's easy to add `punctuation` inside, but both VSCode and GitHub treats dot as a normal character in JSX tag, and there's no other special characters in it, so I think it's not necessary to recognize dot here.

**Comment by RunDevelopment** [comment]
Well, it is as you said, it's easy to add later on.

**Comment by RunDevelopment** [comment]
Thank you for contributing!

**Pull request merged**
