### PR TITLE
Core: Added support for language ids in `inside`

### PR DESCRIPTION
**Pull request by RunDevelopment**
This implements the addition to core described in #2948.

The basic idea is that the `inside` property of grammar tokens should allow language ids (strings) to make it easy to embed other languages and to create recursive languages. This is a relatively common problem and the solutions we have right now aren't pretty.

This is a breaking change because this PR changes the type definition of a grammar. Code relying on grammars having this specific shape will break.

---

I did not change any existing languages to use the new feature in this PR. We can still do this after merging this one.

### CODE REVIEW

**Review by JaKXz — COMMENTED** [review]
Sorry I missed this! Looks great, but I would want to see a minimal example in a test ideally.

**Comment by RunDevelopment** [comment]
> but I would want to see a minimal example in a test ideally.

Good point. I added a test case that checks the behavior of a minimal grammar.

**Review by JaKXz — APPROVED** [review]
🔥

**Comment by JaKXz** [comment]
@RunDevelopment anything preventing this from being merged? I think it'd be a cool release for v1.29 :)

**Comment by JaKXz** [comment]
@RunDevelopment ignore my previous comment - I misread `non-breaking change` instead of `breaking-change`.

Should we start a separate branch for v2.0 and start to get these merged? :)

**Comment by RunDevelopment** [comment]
Implemented in v2.

**Pull request closed without merging**
