### PR TITLE
Allow text change to other languages. Plugin: copy to clipboard

### PR DESCRIPTION
**Pull request by AlexTorresSk**
This allows the value of the text to be changed to other languages, css icon, image, etc.

captura

### CODE REVIEW

**Comment by mAAdhaTTah** [comment]
Thanks! This is definitely something I was planning on implementing as I i18n a plugin I'm working on. However, I don't think we should use global variable to handle this but data-attributes instead.

@Golmote @LeaVerou I don't think we want the translation on every `code` or `pre` instance, although maybe that's fine. What about putting it on the `script` tag itself work? Body tag? Where else? Thoughts?

**Comment by Golmote** [comment]
@mAAdhaTTah Could it be inherited, like the `language-XXX` class is? Therefore any ancestor of a `pre` or `code` could provide the translations attributes.

**Comment by LeaVerou** [comment]
Yes, definitely not globals! Imagine having 200 globals in the future, for 200 phrases.
However, the functionality is definitely useful.
Probably the ideal thing would be to inherit data attributes, like @Golmote suggests.
Such attributes should probably have a prefix, like `data-prism-phrase-copy` or `data-prism-phrases` with a list of key-value pairs separated by colons and commas.

**Comment by AlexTorresSk** [comment]
@LeaVerou and @Golmote Yes. No matter how it is implemented, what I was looking for was the same, that can be translated or written in the language that the user decides.

**Comment by mAAdhaTTah** [comment]
@AlexTorresSk Do you have enough information to take a shot at an implementation here? You can see how inheritance is handled in core [here](https://github.com/PrismJS/prism/blob/gh-pages/components/prism-core.js#L178-L187).

**Comment by mAAdhaTTah** [comment]
Hi @AlexTorresSk, thank you for the contribution. We're definitely not going to go with globals for this, so I'm going to close this PR, but we'd love to merge a fix for this, if you'd be interested in taking it on. If you do, please branch from `master`, as we're in the process of deprecating `gh-pages` and moving everything to `master`.

I've opened #1438 to capture this issue, as it's something we definitely want to address. Please let us know if you have any questions if you do pick this up.

Thanks again!

**Pull request closed without merging**
