### PR TITLE
Use `\d` for `[0-9]`

### PR DESCRIPTION
**Pull request by valtlai**
Like #1107. Also `[\d.]` for `[0-9.]` and `[\d_]` for `[0-9_]`.

### CODE REVIEW

**Comment by RunDevelopment** [comment]
Thank you for the PR @valtlai!

While I do agree that `\d` is better than `[0-9]`, I don't think that replacing `0-9` within character classes like `[0-9a-f]` with `\d` improves readability.

Also, we should probably use the [`regexp/prefer-d`](https://ota-meshi.github.io/eslint-plugin-regexp/rules/prefer-d.html) rule to enforce this. I opened an issue for this: ota-meshi/eslint-plugin-regexp#341

**Comment by RunDevelopment** [comment]
My addition to `regexp/prefer-d` was just merged and will be part of the next release.

**Comment by valtlai** [comment]
I edited this PR to only replace `[0-9]` with `\d`, `[0-9.]` with `[\d.]` and `[0-9_]` with `[\d_]`, so character classes like `[0-9a-z]` are kept as is.

**Review by RunDevelopment — APPROVED** [review]

**Comment by RunDevelopment** [comment]
Thank you for contributing @valtlai!

**Pull request merged**
