### PR TITLE
Add setTimeout fallback for requestAnimationFrame

### PR DESCRIPTION
**Pull request by brentertz**
Address issue #987 - Add `setTimeout` fallback for `requestAnimationFrame`

### CODE REVIEW

**Comment by valtlait** [comment]
`requestAnimationFrame` doesn’t have the second attribute. Can you remove it, please?

**Comment by brentertz** [comment]
Yep, removed.  Not sure why that was in there in the first place or why I didn't notice it.

**Comment by Golmote** [comment]
Indeed. It was there because it originally was a setTimeout and the person who changed it forgot to remove it. 
It went unnoticed because that change was part of an unrelated PR...

**Comment by Golmote** [comment]
Why 16, by the way?

**Comment by brentertz** [comment]
60 frames per second (fps) is the target for smooth animations

1s or 1000ms / 60fps = ~16ms

There are other ways to handle this, mind you.  This is the simplest implementation.  You however may be interested in calculating the value more precisely.  https://gist.github.com/paulirish/1579671

**Comment by zeitgeist87** [comment]
You could also do it with a one-liner:

```js
(requestAnimationFrame || setTimeout)(_.highlightAll, 0);
```

But it would be a bit of a hack and your solution is probably better.

**Comment by Golmote** [comment]
Just noticed you created the PR against the master branch. We currently work on gh-pages. The master is only updated on new release.
I merged this PR manually.

**Pull request closed without merging**
