### PR TITLE
Highlight token class-name with colour #DD4A68

### LINKED ISSUE #1346: Highlight class name in java
Hi, in java it dosent seem to highlight the class name or the one after extends too

screen shot 2018-03-11 at 19 39 30

See ^^

### PR DESCRIPTION
**Pull request by paladox**
Fixes #1346

### CODE REVIEW

**Comment by Golmote** [comment]
Oh I meant add it in _your_ CSS. But I guess we could go through all the official themes to add it...

**Comment by paladox** [comment]
@Golmote yep i know, but would like to add it officially :)

**Comment by paladox** [comment]
thanks :)

**Comment by mAAdhaTTah** [comment]
@Golmote Should we include this in the rest of the themes?

**Comment by Golmote** [comment]
@mAAdhaTTah Yes, I think we should try to make the official themes support the same tokens, indeed.

**Pull request merged**
