### PR TITLE
Add Support for Shortcodes (WordPress)

### PR DESCRIPTION
**Pull request by mccomaschris**
To use this language, use the class "language-shortcode"

### CODE REVIEW

**Comment by RunDevelopment** [comment]
@mccomaschris 
What is the difference between this language and BBCode? I read some articles but they seem pretty much the same to me.

**Comment by mccomaschris** [comment]
> @mccomaschris
> What is the difference between this language and BBCode? I read some articles but they seem pretty much the same to me.

Crap, I had totally missed that one (and not used BBCode, or even thought of it, in over a decade. I'll go ahead and close this for now. Thanks!

**Comment by RunDevelopment** [comment]
One question: Should we give BBCode an alias "shortcode", so you can still use `language-shortcode`?

**Comment by mccomaschris** [comment]
I think it could be beneficial, I tried that language class. I know of a couple very popular WordPress plugins using language-php for their shortcodes in their documentation, they like me may not just put BBCode and WordPress Shortcodes together as the same language. I'll submit a new PR to add "shortcode" as an alias to BBCode.

**Pull request closed without merging**
