### PR TITLE
Swift: Major improvements

### PR DESCRIPTION
**Pull request by RunDevelopment**
I made a number of changes to Swift:

1. Added support for nested comment (`/* /* foo */ */`).
1. Added support for multi-line strings (`""" foo """`) and raw strings (`#" foo "#`)
1. Removed single-quoted strings. Swift does not and has never supported single-quoted strings.
1. Correct tokenization for all operators + punctuation.
1. Added "omit" rule for `_`.
1. Added support for statement labels. (`foo: while ...`)
1. Removed builtin functions/properties. They just looked out of place and provided no real value.
1. Improved function detection.
1. Naming-based type detection. All type-like structures (classes, structs, protocols, etc.) typically have UpperCamelCase names.

Edit:

10. Support directives.
11. Support all/custom attributes.
12. Updated keywords.

---

@AvdLee 
I hope this helps with #3021.

Also, I'm not familiar with Swift and not sure about the naming-based class detection. Can we assume that everything starting with an upper-case letter and containing a lower-case letter is a class name?

### CODE REVIEW

**Comment by AvdLee** [comment]
> Also, I'm not familiar with Swift and not sure about the naming-based class detection. Can we assume that everything starting with an upper-case letter and containing a lower-case letter is a class name?

It's fair to say yes, but Swift doesn't enforce us doing so. I haven't seen any code examples though in which developers defined classes starting with a lowercase!

**Comment by AvdLee** [comment]
> @AvdLee
> I hope this helps with #3021.

Really impressive PR! Thanks a lot, I'm learning a lot about this library as well now 🙂  
I'm sure we're getting closer and closer to better support!

Btw, if you like to explore how Prism is behaving with Swift, you can check out my articles here: avanderlee.com
All highlighted code is backed by Prism 💪

**Comment by RunDevelopment** [comment]
@AvdLee I think I got everything from #3021 now.

Also, in your article about [dependency injection](https://www.avanderlee.com/swift/dependency-injection/), you presented this attribute: `@Injected(\.networkProvider)`. What does the `\.` mean?

**Comment by AvdLee** [comment]
> @AvdLee I think I got everything from #3021 now.

Dang, that's amazing! Thanks a ton 💪 

> Also, in your article about dependency injection, you presented this attribute: @Injected(\.networkProvider). What does the \. mean?

It's an accessor to a key path reference. See "Key-Path Expression" in this document: https://docs.swift.org/swift-book/ReferenceManual/Expressions.html

**Comment by RunDevelopment** [comment]
> It's an accessor to a key path reference.

Seems like I missed that part while scanning through the docs. Thank you!

**Pull request merged**
