### PR TITLE
Added a Coy bug to the known failures page.

### PR DESCRIPTION
**Pull request by RunDevelopment**
As discussed [here](https://github.com/PrismJS/prism/issues/2164#issuecomment-572558797).

image

---

I also quickly looked for other open theme issue but couldn't find any. If there are any I missed, please leave a comment.

### CODE REVIEW

**Comment by garretwilson** [comment]
Actually @RunDevelopment I discovered another Coy shadow bug, this time vertically!. If you have two flexbox items (this is very important to me to include code snippets in flexbox children!), the code snippit will only extend vertically as much as it needs, but the shadow will extend vertically to fill the flexbox!

prism-coy-shadow-flex-bug

The overall problem is that you seem to be using two different approaches to sizing the code section and the shadow. It seems to be that if this keeps appearing, there's a fundamental flaw in the approach.

The shadow should match the code area, both horizontally and vertically.

As I mentioned before I'm going to turn the shadow off across all my pages, but it's a shame and I think you should revisit how you do the shadow.

**Comment by RunDevelopment** [comment]
So we can go in both directions... At least it's consistent.

But this seems to be the same bug just cause by flex(ing) this time.

> It seems to be that if this keeps appearing, there's a fundamental flaw in the approach.

There is. For Coy, the `pre` is just a wrapper and all styling is done on the `code` element. This is basically the opposite of what all other themes are doing and one of the reasons why we have so many Coy-related issues.
It's actually quite simple to rewrite the themes to style the `pre` making it behave like all others but I can't get the shadows working. [More details](https://github.com/PrismJS/prism/issues/2164#issuecomment-572184378).

> I'm going to turn the shadow off 

I am curious about how you do this. Do you just disable the pseudo-elements and make the background transparent or do you actually fix the layout (if so, how)?

**Comment by garretwilson** [comment]
> > I'm going to turn the shadow off

> I am curious about how you do this. Do you just disable the pseudo-elements and make the background transparent or do you actually fix the layout (if so, how)?

I'm just following the [instructions](https://github.com/PrismJS/prism/issues/894#issuecomment-184317382) in #894 (which I opened after all the Coy shadow problems in #859).

It had been so long that I had forgotten all the pain the shadows caused, and tried to turn them back on. Now they are on across all my sites and I'll have to go back and turn them off again. It will be wonderful to have the bugs publicly documented so I won't make that mistake again.

**Comment by mAAdhaTTah** [comment]
If there's an alternate approach you have in mind, we could possibly put it in [`prism-themes`](https://github.com/PrismJS/prism-themes) as like a `coy-alt` or something. Alternatively, I would accept `coy-without-shadows` there as well (although preferably only one of those).

**Comment by garretwilson** [comment]
Thanks, but frankly this is the least of my worries at the moment. As long as I have a way to turn it off, I can concentrate on other problems. I think `coy-without-shadows` is a hack, but it does point out that there may be variations needed to some of the themes. So you might want to think about that in a general sense going forward; maybe each of the themes have customizable options on the download page or something.

In any case the most important thing for the short terms is to document the problems in a visible way and explain how to turn the shadows off.

**Comment by RunDevelopment** [comment]
> I'm just following the instructions in #894 (which I opened after all the Coy shadow problems in #859).

And that works? I see that it disables the shadows but it doesn't change the background, so it should still be able to overlap with other elements if I'm not mistaken. I'll look into it.

**Comment by garretwilson** [comment]
> And that works?

I haven't tried it in a while. When I last tried it I was using an old version of Prism. I just assumed it still worked. If not we have a bigger problem.

If it doesn't work then maybe you should provide a version of Coy after all that uses the same technique as the other themes but without the shadow.

**Comment by garretwilson** [comment]
> it should still be able to overlap with other elements if I'm not mistaken.

I think the Coy theme always overlapped other elements, correct? That's why usually I would float the Prism block e.g. to the left if I had something I wanted it to wrap around.

This problem with the shadow is not that the code block overlapped with a float (because that always happened, unfortunately), but that the shadow didn't match up with the code block dimensions and therefore didn't look like a shadow.

**Comment by RunDevelopment** [comment]
Yes, they still overlap.

<details>

image

</details>

I'll make a PR for a version of Coy without shadows.
Only problem: Right now, the download page doesn't support themes from Prism themes... This will be a little harder to bring to the download page.

**Comment by garretwilson** [comment]
> Yes, they still overlap.

I can't say 100%, but I'm pretty sure that two or three years ago the overlap would occur but _the code would also extend to fill that white space_!

So did something change in the past couple of years? If as you say the `<pre>` is a block element and shouldn't wrap around the floats, then why is the Coy code section cut of or pushed to the left? I would almost swear that it didn't use to work like that.

**Comment by garretwilson** [comment]
See, look at #866. I'm pretty sure that the Coy theme would reach right through the float. Why doesn't it work that way anymore? One could argue that this is the correct behavior, even though I don't like it.

**Comment by garretwilson** [comment]
In fact #866 wouldn't be so bad if I could change the Z order somehow and have my floats go _on top_ of Prism.

**Pull request merged**
