### PR TITLE
MongoDB: added v5 support

### PR DESCRIPTION
**Pull request by airs0urce**
Added support for MongoDB 5 keywords

### CODE REVIEW

**Review by RunDevelopment — APPROVED** [review]

**Comment by RunDevelopment** [comment]
Thank you for contributing @airs0urce!

And for the future: Please don't spam PRs...

**Comment by airs0urce** [comment]
> Thank you for contributing @airs0urce!
> 
> 
> 
> And for the future: Please don't spam PRs...

Thanks!

I was closing PRs after I see tests not passed. If there is way to check tests results before creating PR it would help me to check it before. But I'm not sure if this is possible now.

**Comment by RunDevelopment** [comment]
You can add as many commit as you want, even after creating a PR. The PR will be updated automatically after you push new commits. So if the tests fail, just keep adding commits until they pass.

> way to check tests results

If you want to run tests locally, run `npm run test`. This will run our unit tests.
In your case, the lint failed. This test can be run using `npm run lint`.

Our CI also runs some additional tests, but the above two are the most important ones.

**Comment by airs0urce** [comment]
> You can add as many commit as you want, even after creating a PR. The PR will be updated automatically after you push new commits. So if the tests fail, just keep adding commits until they pass.
> 
> > way to check tests results
> 
> If you want to run tests locally, run `npm run test`. This will run our unit tests. In your case, the lint failed. This test can be run using `npm run lint`.
> 
> Our CI also runs some additional tests, but the above two are the most important ones.

Thank you for the info, will do like that next time. I send PRs not often on github, so didn't get used to the procedure.

**Pull request merged**
