### PR TITLE
.npmignore: Unignore components.js

### PR DESCRIPTION
**Pull request by papandreou**
For the trick suggested by @apfelbox in https://github.com/PrismJS/prism/issues/593#issuecomment-219856317 to work, we need both of these files to be in the NPM package:

* /components.js
* /tests/helper/components.js

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thanks!

PS: Nice username :P

**Comment by papandreou** [comment]
Thanks :)

> PS: Nice username :P

That's not the usual reaction from Greeks! (eg. https://github.com/less/less.js/issues/462#issuecomment-3814595)

**Comment by LeaVerou** [comment]
> That's not the usual reaction from Greeks!

Haha, I thought you chose it ironically :) Also that dude seriously needs to chill, geez.

**Comment by papandreou** [comment]
> I thought you chose it ironically

It's actually been with me since I was a kid. My name is Andreas and my parents thought that "Andreas Papandreou" sounded cute. Seemed innocent enough until those real Papandreous got into all those scandals and bankrupted the country ;)

**Comment by LeaVerou** [comment]
> Seemed innocent enough until those real Papandreous got into all those scandals and bankrupted the country ;)

True, though they also passed many laws to bring the country up to date with other developed countries, such as the gender equality laws of 1983, or civil marriage in 1982. I dislike PASOK as much as the next person, but they did some good things too, για να λέμε και του στραβού το δίκιο :)

**Pull request merged**
