### PR TITLE
Keep the highlighted handlebars code if there are more plugging, e.g.…

### PR DESCRIPTION
**Pull request by janvanhelvoort**
… line-numbers.

### CODE REVIEW

**Comment by Golmote** [comment]
I'm not sure I understand the issue this PR is supposed to fix... Can you provide an example?

**Comment by janvanhelvoort** [comment]
if you have a code block with the following layout, E.g.
```
<pre class="line-numbers"><code class="language-handlebars">{{template}}</code></pre>
```
In the 'Line-Number' plugin, on the following lines [#40 - #42](https://github.com/PrismJS/prism/blob/95dc10296922e7666b75428ea89359ee93d95e62/plugins/line-numbers/prism-line-numbers.js#L40-L42), the output is set on `env.element`.

If you use it with handlebars syntax highlight, the added code from the 'Line-Numbers' plugging is removed, because on line [#75 - #79](https://github.com/PrismJS/prism/blob/95dc10296922e7666b75428ea89359ee93d95e62/components/prism-handlebars.js#L75-L79) the code is overwritten. It uses `env.highlightedCode` instead of `env.element`.

The fix of mine, takes `env.element.innerHTML` if it is there, otherwise it will take the `env.highlightedCode`

**Comment by Golmote** [comment]
Can you take a look at this Fiddle? It uses the code you just provided with the line numbers plugin. And I can't see any problem.

**Comment by janvanhelvoort** [comment]
Strange, in your example, it works, in our project, it isn't working,
Can I mail jou the project?

**Comment by janvanhelvoort** [comment]
I see it, on you site: Prism-line-numbers.js rule #1: `Prism.hooks.add('complete', function (env) {`
If i get it from Bower, rule #1 `Prism.hooks.add('after-highlight', function (env) {`

but on git, the correct line is displayed ( `Prism.hooks.add('complete', function (env) {` )
Bower is serving old code?

and it uses the wrong git: `git://github.com/LeaVerou/prism.git#~1.0.1`

**Comment by janvanhelvoort** [comment]
`$ bower install 'git://github.com/PrismJS/prism#gh-pages' --save` works for now :+1: 

```
  "dependencies": {
    "prism": "git://github.com/PrismJS/prism#gh-pages"
  },
```

**Comment by Golmote** [comment]
The "complete" hook is a really recent change. It is not part of release 1.0.1.
gh-pages is always the most up-to-date branch, but we're trying to sync master regularly.

**Pull request closed without merging**
