### PR TITLE
added github theme

### PR DESCRIPTION
**Pull request by aviaryan**
A theme inspired from syntax-highlighting on github. I have tested it on AutoHotkey, Ini, CSS, Javascript and Python and it looks nice if not identical in some cases.

### CODE REVIEW

**Comment by jtappa** [comment]
Was anything ever decided in relation to this and having a separate repo for extra themes? Because my team would also appreciate having a github theme for live previews in MacDown.

**Comment by aviaryan** [comment]
An extra repo (like prism-themes) will be nice.

**Comment by LeaVerou** [comment]
Yes it would… If it’s just a repo, I can make it, but it would be awesome if it also had a site with previews and even ratings! But who has time to build that… (I certainly don’t \*sob\* :( )

**Comment by apfelbox** [comment]
@LeaVerou how about creating a Github organisation and including `prism` and `prism-themes` repositories?

**Comment by Golmote** [comment]
@LeaVerou Well, first create the repo. We'll see if anyone can do a website, next. Some screenshots of the available themes in the README could probably be enough to begin with.

**Comment by LeaVerou** [comment]
Done! :)

**Comment by apfelbox** [comment]
@LeaVerou you could add yourself to the organization ;)

As we are cleaning up the repositories -- this could be the time to separate the website and core into different repositories. I will try to come up with a working solution.

**Comment by LeaVerou** [comment]
What do you mean? I have added myself to the organization when I created it… Should I add you too? I hadn’t seen you around for a while :)

**Comment by apfelbox** [comment]
@LeaVerou I just saw "This organization has no public members." :wink: 

I was heavily time-constrained by more work in the university and my work at... well, work. I am currently planning on writing up my thoughts on a possible clean up and modernization of some of the code (which would bring its own caveats, therefore the write-up). I will be able to invest more time in my OSS work, so you probably will read more from me again in the future.

**Comment by Golmote** [comment]
@aviaryan: I just added your Github theme to the [prism-themes repo](https://github.com/PrismJS/prism-themes).
I added a few tokens to handle git and markdown better (`inserted`, `deleted`, `bold`, `italic`).

**Comment by Golmote** [comment]
> Highlighting of JS and CSS inside HTML doesn't happen. Maybe it's because I am using individual js files instead of a pack.

BTW, this is because Markup must be included before CSS and JS for this to work properly.

**Comment by aviaryan** [comment]
@Golmote Thanks. I will look forward to it.

**Pull request closed without merging**
