### PR TITLE
Support for JavaScript octal and binary numbers (in ES6)

### PR DESCRIPTION
**Pull request by apfelbox**
This will add support octal and binary numbers:

```js 
var a = 0o01234567;
var b = 0o101;
```

I also removed a duplicate negative sign for `Infinity`.

Fixes part of #111

### CODE REVIEW

**Comment by apfelbox** [comment]
You can merge #596 before this one, so I can rebase my PR based on these javascript changes.

**Comment by Golmote** [comment]
I just merged #596. Let me know when this PR is updated.

**Comment by apfelbox** [comment]
So, i just rebased and squashed the changes in one commit.

Ready to be merged @Golmote

**Comment by Golmote** [comment]
Sorry, can you do it again?

**Comment by apfelbox** [comment]
@Golmote no problem, done.

**Comment by loganfranken** [comment]
Hey @vkbansal, maybe I'm wrong, but it doesn't look like operators are highlighted as part of numbers with Prism currently:
http://codepen.io/loganfranken/pen/gpxaLe

So it would seem to fall in line that `-Infinity` shouldn't be highlighted as a number (if the minus operator in `-123` isn't highlighted as number, for example).

Totally let me know if I'm missing something, though!

**Comment by apfelbox** [comment]
@vkbansal @loganfranken even easier than that. If you take a closer look at the braces in the regex, that only `Infinity` has a negative sign. That is because that whole match already has a negative sign at the beginning – and therefore the one in `Infinity` is duplicate.

2015-06-14 at 21 31

@loganfranken you are right, the regex matches it, but it isn't included in the token. Because of this it will be highlighted as operator later on.

**Comment by loganfranken** [comment]
@apfelbox Ahh, thanks for clearing that up!

**Comment by vkbansal** [comment]
@apfelbox thanks for the clarification :)

**Pull request merged**
