### PR TITLE
Add support for Here-Documents for the Bash language

### PR DESCRIPTION
**Pull request by zeitgeist87**
This patch adds support for Here-Documents for the Bash language.
A Here-Document should be highlighted as a multiline string
and looks like this:

```bash
cat << EOF
foo bar
EOF
```

I have also cleaned up the Bash language a little bit. I have put those changes into separate commits to make the review easier.

### CODE REVIEW

**Comment by Golmote** [comment]
Thank you for working on this.

Can you rename the test file from `important_feature.test` to `shebang_feature.test`?

**Comment by zeitgeist87** [comment]
> Can you rename the test file from important_feature.test to shebang_feature.test?

Sure, I just updated the PR.

**Comment by Golmote** [comment]
Thanks!

**Comment by sunknudsen** [comment]
@zeitgeist87 

Thanks for this PR! Do you know how to fix here-document support in the shell-session language?

Currently, everything after `cat` is registered as the output.

here-document

**Pull request merged**
