### PR TITLE
Npm:  Fixed mocha and gulp-uglify vulnerabilities

### PR DESCRIPTION
**Pull request by RunDevelopment**
This brings mocha (`2.2.5` -> `5.2.0`) and gulp-uglify (`0.3.1` -> `3.0.1`) to the latest versions and fixes 5/11 vulnerabilities.
(I only changed `package.json`)

Almost all minified are different because of the uglify update.
Keep in mind merging this will create conflicts for almost every other PR because of the minified files.

I will upgrade gulp (`3.8.6` -> `4.0.0`) once this and #1741 are through because `gulpfile.js` has to be changed.

### CODE REVIEW

**Comment by mAAdhaTTah** [comment]
Didn't we upgrade to gulp 4 already?

**Comment by RunDevelopment** [comment]
Yes, but only `gulp`. This updates `mocha` and `gulp-uglify`.

**Comment by mAAdhaTTah** [comment]
Can we go straight to mocha@6?

**Comment by RunDevelopment** [comment]
I updated __all__ dependencies now and everything works just fine.

I just wonder why the minified files changed again...

**Pull request merged**
