### PR TITLE
[PHP] Add `match` keyword in PHP 8.0

### PR DESCRIPTION
**Pull request by Ayesh**
PHP introduces a new [`match` keyword in PHP 8.0](https://php.watch/versions/8.0/match-expression).
This commit updates the keywords list for PHP language component to add `match` to it.

Thank you.

### CODE REVIEW

**Review by RunDevelopment — CHANGES_REQUESTED** [review]
Thank you for this pull.

Please also add this keyword to [PHP's keyword test](https://github.com/PrismJS/prism/blob/master/tests/languages/php/keyword_feature.test).

**Comment by Ayesh** [comment]
Thanks a lot for the quick response @RunDevelopment , I will make changes there soon. I apologize for not having it in one go.

**Comment by Ayesh** [comment]
I updated the tests @RunDevelopment. Thank you.

**Comment by RunDevelopment** [comment]
Thank you for contributing @Ayesh!

**Pull request merged**
