### PR TITLE
SQL: Quoted variables are now greedy

### LINKED ISSUE #1509: Single-quoted variables not working for SQL highlighting
According to the examples, the following should work, but it does not
`SET @'quoted-variable' = 3; `
All other quoted variable examples do work, i.e. the following:
```
SET @variable = 1;
SET @$_ = 2;
SET @"quoted-variable" = 3;
SET @`quoted-variable` = 3;
```

### PR DESCRIPTION
**Pull request by RunDevelopment**
This resolves #1509.

---

I added a small fix to bypass #1492.
It now (mostly) works because the quoted variables are now matched before strings. Therefore strings (of quoted variables) are always contained by the variable which leads to there match being discarded.

This little trick also reduces the greedy matching overhead because it doesn't have to rematch any patterns. Maybe we should include this trick into the docs as a best practice?

### CODE REVIEW

**Comment by mAAdhaTTah** [comment]
Got conflicts here, probs a result of the other SQL PR I just merged.

**Comment by mAAdhaTTah** [comment]
Are there styles for `quoted-variable`? I don't _think_ that's a currently-existing token...

**Comment by RunDevelopment** [comment]
I know any styles for `quoted-variable` either. It's just a temporary name because it has to be matched before `string`.
But we could move `variable` before `string` as well and merge the two into one `variable` token without any side effects (I think).

**Comment by RunDevelopment** [comment]
I did implement the merged `variable` token.

Is it ready to merge?

**Pull request merged**
