### PR TITLE
Fix the PHP language

### PR DESCRIPTION
**Pull request by zeitgeist87**
This patch is an attempt to fix the PHP language, when it is combined
with markup.

The problem is, that markup has a higher priority than all other tokens.
This leads to weird errors, where HTML tags are highlighted inside of
comments #197. One solution to this was to set the `greedy` flag for the
comment token, but this leads to far worse errors like #1097.

This patch should fix both issues #197 and #1097, by switching the
grammar to markup on the fly. One potential problem is, that it relies
on the `<?php` tag to detect if markup is present. So if a PHP file
contains only markup and no PHP code at all, the result will look
broken.

### CODE REVIEW

**Comment by zeitgeist87** [comment]
Before (Note: The JavaScript function is erroneously highlighted by PHP. CSS is not highlighted at all. Strings inside comments do not work):
before

After (Note: The string `"px"` looks different, because CSS has custom styles for the class `token string`. JavaScript and CSS are highlighted by the correct language.) :
after

**Comment by zeitgeist87** [comment]
There is one problem with this PR. If there are no `<?php` tags, then it assumes, that it is pure PHP code, which could be wrong:
wrong
correct2

If a `<?php` tag is present, then markup is also highlighted:
correct

**Comment by zeitgeist87** [comment]
@LeaVerou @Golmote What do you think about this PR?

**Comment by LeaVerou** [comment]
> If there are no <?php tags, then it assumes, that it is pure PHP code, which could be wrong:

I don't think that's a huge problem (they can use `markup` in those cases), as long as it supports the shortened PHP tags as well (`<?=` etc). Though I don't see why we can't check if a PHP tag is present and use the markup definition if not.

**Comment by zeitgeist87** [comment]
> Though I don't see why we can't check if a PHP tag is present and use the markup definition if not.

Yes that is one option, but I think it is more intuitive to assume that it is all PHP in that case. For example someone could use small snippets of PHP code between paragraphs on a blog to explain a larger file:

```php
$test = "<div>" . $_SERVER['PHP_SELF'] . "</div>";
```

If we switch to `markup` in that scenario, we would force the users to put PHP tags around every small snippet:

```php
<?php $test = "<div>" . $_SERVER['PHP_SELF'] . "</div>"; ?>
```
If there is no PHP code at all, people should use `markup` directly.

**Comment by LeaVerou** [comment]
Ah yeah, excellent point! Completely agree.

**Comment by Golmote** [comment]
@zeitgeist87 Sorry for the looong time before review. This looks ok to me! ;) Feel free to merge.

**Comment by zeitgeist87** [comment]
@Golmote Thanks again for the review! Merging...

**Pull request merged**
