### PR TITLE
Set type="button" attribute for copy to clipboard plugin.

### PR DESCRIPTION
**Pull request by alexsegura**
Hi. 

When using Prism + copy to clipboard inside a HTML form, the form is submitted when copying. 
It's because by default the button is seen as a submit button. 
Adding the `type="button"` attribute prevents this.

### CODE REVIEW

**Comment by mAAdhaTTah** [comment]
Makes sense. Thanks for the contribution!

**Comment by alexsegura** [comment]
🙌

@mAAdhaTTah is a new release planned anytime soon?

**Comment by RunDevelopment** [comment]
@mAAdhaTTah I think a new release after #2584 might be a good idea. I'm waiting for a confirmation from @yetingli that all vulnerabilities have been fixed but I'm reasonably confident that there won't be many others because of #2590.

**Comment by mAAdhaTTah** [comment]
@RunDevelopment I'm on board with that. We did a release recently, so maybe next one should be a patch?

**Comment by RunDevelopment** [comment]
@mAAdhaTTah Yeah. All commits since v1.22.0 were enhancements and bug fixes, so I agree that it should be a patch.

**Pull request merged**
