### PR TITLE
Cilk: Add support for Cilk (with C/C++)

### PR DESCRIPTION
**Pull request by ailiop**
This PR adds support for the [Cilk](https://en.wikipedia.org/wiki/Cilk) language extension to C/C++, specifically the set of keywords supported by the latest version of the [OpenCilk](https://opencilk.org) platform.  I have followed the various instructions in the [README](https://github.com/PrismJS/prism).

### Summary

The entirety of the specification is only a few lines.  It just creates 2 new languages by extending C and C++ with the parallel keywords `cilk_for`, `cilk_reducer`, `cilk_scope`, `cilk_spawn`, and `cilk_sync`.  I used the `insertBefore()` function to add the new token label before `function` to capture Cilk keywords which are followed by arguments in parentheses.

### Ownership

I specified the [OpenCilk GitHub organization](https://github.com/OpenCilk) (of which I am a part) as the "owner" in `components.json`.  I plan to be handling future bug reports related to the `cilkc` and `cilkcpp` languages, but I believe that listing the OpenCilk organization as the owner should ensure better coverage and continuity as the Cilk language evolves.

### CODE REVIEW

**Comment by RunDevelopment** [comment]
Thank you for the PR @ailiop!

The code itself looks good. Due to old infrastructure, you also have to commit the minified files generated by `npm run build` (this is why the CI fails). After that, this PR is good to go.

**Comment by ailiop** [comment]
Thank you and sorry for the extra trouble.  I had not realized the build-generated files were necessary.

I believe the PR should be ready now.

**Comment by ailiop** [comment]
Oh, and thank you for making it easy — and well documented — to add a language definition/extension to Prism!

**Comment by RunDevelopment** [comment]
Thank you for contributing!

> sorry for the extra trouble. I had not realized the build-generated files were necessary.

No worries. It's not exactly common. Thank you for putting up with it :)

**Pull request merged**
