### PR TITLE
TOML support

### LINKED ISSUE #1436: Support for TOML
[TOML](https://github.com/toml-lang/toml) is a data markup language like YAML or JSON. It's increasingly used for configuration files in tools like Hugo and Netlify.

For reference in adding support, here's the TOML definition file for the Chroma syntax highlighter:
https://github.com/alecthomas/chroma/blob/master/lexers/t/toml.go

### PR DESCRIPTION
**Pull request by RunDevelopment**
This PR adds support for [Tom's Obvious, Minimal Language](https://github.com/toml-lang/toml).

I made some simplifications:

1. The `.`s of dotted keys are not highlighted. This is because the `.` could be inside quotes and checking that isn't easy.
2. There is no distinction between table `[foo]` and array `[[foo]]`. `foo` will be highlighted as `table` in both cases.

This PR resolves #1436

### CODE REVIEW

**Comment by RunDevelopment** [comment]
@mAAdhaTTah 

Test were added.

I'm looking forward to the review.

**Comment by RunDevelopment** [comment]
@mAAdhaTTah 

It's the label supposed to be `needs review` ?

**Comment by mAAdhaTTah** [comment]
Yeah, switched to needs review.

**Comment by johng-cn** [comment]
How it is going, I am quite looking forward to this feature.

**Comment by RunDevelopment** [comment]
@johng-cn 
Well, I'm looking forward to this too but someone has to thoroughly review it. Unfortunately, @Golmote is quite busy right now, so it might take a little while.

**Comment by mAAdhaTTah** [comment]
If we get the conflicts resolved, we can merge this.

**Comment by verythorough** [comment]
Thanks, @RunDevelopment!

**Pull request merged**
