### PR TITLE
Changelog v1.23.0

### PR DESCRIPTION
**Pull request by RunDevelopment**

### CODE REVIEW

**Comment by mAAdhaTTah** [comment]
@RunDevelopment Oh, that reminds me: Did we include a fix for the regex we were notified about?

**Comment by RunDevelopment** [comment]
@mAAdhaTTah Now that you mention it. The fix is trivial, so I'll just make a quick PR and merge it. We can decide on a security advisory later.

**Comment by RunDevelopment** [comment]
Done. The changelog has been updated accordingly.

**Comment by RunDevelopment** [comment]
@mAAdhaTTah After [this comment](https://github.com/PrismJS/prism/pull/2682#issuecomment-752924296), I am currently implementing an improvement for the detector, so that it will check (hopefully) all of Prism's regexes. I have already found that half of Latte is unchecked due to the nature of markup templating. Other languages that use markup templating (e.g. PHP) might also be affected.

Let's please hold the release until I have verified that there are no other detectable cases of exponential backtracking in Prism's code base.

**Comment by RunDevelopment** [comment]
@mAAdhaTTah I found one more with exponential backtracking. I'll make separate PRs for the fix and the improved test suite.

**Comment by RunDevelopment** [comment]
@mAAdhaTTah I merged the fix. The PR for the improved test suite and be dealt with after the release. I think there's nothing holding up the release now.

**Review by mAAdhaTTah — APPROVED** [review]
@RunDevelopment Thanks for doing this! Gonna publish this now.

**Pull request merged**
