### PR TITLE
Add support for NSIS 3.03, bug-fixes

### PR DESCRIPTION
**Pull request by idleberg**

### CODE REVIEW

**Comment by Golmote** [comment]
Hi @idleberg! Thanks for contributing again!
Could you please not remove the `?:` parts? They were intended, as all those captures are not required.
Only the two occurrences of `(^\s*)` are required to be captured for the `lookbehind` feature to work.

**Comment by Golmote** [comment]
You misunderstood me. The `?:` should **not** be removed.

**Comment by idleberg** [comment]
I don't see which commit (prior to b490d6a29611be3e4a50102e85aced75bda50968) removed any `?:`

**Comment by Golmote** [comment]
Hm... The global diff on the PR tells differently.
Are you working from an up-to-date branch? The `?:` are in [the current NSIS file](https://github.com/PrismJS/prism/blob/gh-pages/components/prism-nsis.js), but are not in your first commit (a98c16b3e76f5a7320e22bcc23d3a13c14b0d2df).

**Comment by idleberg** [comment]
You were right, my fork was not up-to-date. Closing in favour of #1288

**Pull request closed without merging**
