### PR TITLE
Core: `insertBefore` will now update all references

### PR DESCRIPTION
**Pull request by RunDevelopment**
This removes a condition the reference update logic in `insertBefore`. All references will now be updated, no matter the name of the key.

### CODE REVIEW

**Comment by mAAdhaTTah** [comment]
Why is this needed?

**Comment by RunDevelopment** [comment]
Sorry, I forget to reply. 

I removed this line because it's unnecessary. `value === old && key != inside` means "all values which key is `inside` will not be replaced". 
This doesn't make sense for two reasons: Firstly, the entry in `Prism.languages` is already replaced in the line about (`root[inside] = ret;`) and secondly, why wouldn't you want to replace an old reference just because of its key?

**Comment by mAAdhaTTah** [comment]
> Firstly, the entry in Prism.languages is already replaced in the line about (`root[inside] = ret;`)

My guess is this is why the check exists. We're already replacing `inside`, so we don't need to do it again.

**Comment by RunDevelopment** [comment]
> My guess is this is why the check exists. We're already replacing inside, so we don't need to do it again.

That's also what I interpreted its purpose to be but it really doesn't matter where we set a reference again or not. 

Btw. We can't remove `root[inside] = ret;` because we can't guarantee that `root` is reachable from `Prism.languages`.

**Comment by mAAdhaTTah** [comment]
So if it's fine as-is, I'm going to lean on "less churn" as my preference here and say this isn't really needed.

**Pull request closed without merging**
