### PR TITLE
Pattern builder

### PR DESCRIPTION
**Pull request by RunDevelopment**
This PR is an implementation of #1476.

I decided to make a new namespace `Prism.patterns` (\*hint\* \*hint\* #1494) to keep things organized because `build` doesn't really belong in any of the other namespaces.

The validation method of the base pattern and replacements is located in a new file called `tests/helper/prism-core-tester.js`.
This file's purpose is to add testing functionality to existing Prism methods __only__ when running `npm test`. This has the following advantages:

- `prism-core.js` stays small but still validates on all tested components.
- The validation is not done on our client's computers.

---

Maybe we should make this a resource (#1539)?

---

Btw. This and #1537 go together really well.

### CODE REVIEW

**Comment by RunDevelopment** [comment]
It intrigues me that the build failed despite the fact that I only changed some comments...

It seems like the `npm install -g gulp` command took longer than 10 minutes. How can that be?
Node v6 took each about 7 minutes for `npm install` and `nom install -g gulp`.

**Comment by RunDevelopment** [comment]
Now it worked again.
And it took at most 20 seconds for the `npm install` commands.

**Comment by mAAdhaTTah** [comment]
Travis does weird stuff sometimes. I wouldn't worry too much about it.

**Comment by RunDevelopment** [comment]
This is just an idea for now but with ES6 [tagged template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) we could make a function `Prism.regex` which will behave like `Prism.patterns.build` but has a nice syntax:

```js
const foo = /\bfoo\b/;

Prism.regex`\w\s${foo}\s`; // returns /\w\s(?:\bfoo\b)/

// instead of
Prism.patterns.build(/\w\s<<0>>/, [foo]);
```

There a few drawbacks (flags, browser compatibility, no regex syntax highlighting) but maybe someone likes it.

**Comment by RunDevelopment** [comment]
Closed in favor of #2190.

**Pull request closed without merging**
