### PR TITLE
Tests: Refactoring

### PR DESCRIPTION
**Pull request by RunDevelopment**
I refactored all test related files to use ES6 features.

### CODE REVIEW

**Comment by mAAdhaTTah** [comment]
My only concern about this is it's a little weird to only allow ES6 in the tests but not in the core of the library. Maybe we can enforce this with ESLint?

**Comment by RunDevelopment** [comment]
Why is this weird? Everything made exclusively for a node environment is ES6 and the code which is also available for browser is ES5.

Well, we could use Babel to solve this and make everything ES6 or we could wait for #1578.

> Maybe we can enforce this with ESLint?

Enforce what?

**Comment by mAAdhaTTah** [comment]
I'm pretty sure we can enforce es5 env in the core / languages / plugins area and enable es6 env in the tests with ESLint.

**Comment by mAAdhaTTah** [comment]
It's weird mostly cuz, as a developer, I have to remember "I'm in core, I can only use ES5" to "now I'm in tests, I can use ES6+".

**Comment by RunDevelopment** [comment]
We enforce ES5 for core / languages / plugins already because Uglify doesn't support ES6.

**Pull request merged**
