### PR TITLE
Add `node` to known bash commands

### PR DESCRIPTION
**Pull request by jamesgpearce**
`node` seems like a good command to syntax highlight.

`npm` was already there so I figure this is not very controversial.

### CODE REVIEW

**Comment by RunDevelopment** [comment]
Thank you for the PR @jamesgpearce!

Seems like the build is failing. Just run `npm ci && npm run build` and commit the changes to `prism-bash.min.js` to fix this.

**Comment by jamesgpearce** [comment]
ha; let me squash the commits together

**Comment by jamesgpearce** [comment]
(@RunDevelopment you presumbly need to kick off the CI again)

**Review by RunDevelopment — APPROVED** [review]

**Comment by RunDevelopment** [comment]
Thank you for contributing @jamesgpearce!

**Pull request merged**
