### PR TITLE
.ino is main file extension for arduino files

### PR DESCRIPTION
**Pull request by Outreach-ChemEng-UofU**

### CODE REVIEW

**Comment by joshgoebel** [comment]
Interesting, does Prism do aliases like this?

**Comment by Outreach-ChemEng-UofU** [comment]
> Interesting, does Prism do aliases like this?

I looked at the python language and that's how they handled py and python

**Comment by joshgoebel** [comment]
Ruby also. `Prism.languages.rb = Prism.languages.ruby;`

Perhaps you are right. :)  Just wasn't aware of this.

**Review by RunDevelopment — CHANGES_REQUESTED** [review]
Thank you for the PR @Outreach-ChemEng-UofU!

To add an alias, you also have to register it in [`components.json`](https://github.com/PrismJS/prism/blob/bb93fac0409f768e4c5d6d4b9d2310840f2c2866/components.json#L132) using the `"alias"` property. You also have to rebuild Prism by running the command `npm ci && npm run build`.

---

@joshgoebel Yes, this is how Prism currently does aliases.

**Comment by RunDevelopment** [comment]
Thank you for contributing @Outreach-ChemEng-UofU!

**Pull request merged**
