### PR TITLE
TSX: Temporary workaround for the collisions of JSX tags and TS generics

### PR DESCRIPTION
**Pull request by RunDevelopment**
This implements [the workaround](https://github.com/PrismJS/prism/issues/2594#issuecomment-710666928) proposed by @karlhorky.

(I also had to change the JSX tag pattern to get rid of the backreferences.)

This also fixes TSX's global namespace pollution.

### CODE REVIEW

**Comment by karlhorky** [comment]
Nice, thanks! Will the version with this be `1.22.1`?

**Comment by RunDevelopment** [comment]
This will be part of 1.23.0 but before that, we will merge a few more PRs.

**Comment by karlhorky** [comment]
Sounds good, cheers :)

**Comment by badsyntax** [comment]
Just want to say this change has fixed things for me. See https://github.com/sergioramos/remark-prism/issues/85

Thanks for the fix!

**Pull request merged**
