### PR TITLE
Highlight Elixir string markdown header correctly

### PR DESCRIPTION
**Pull request by danielberkompas**
Elixir allows markdown inside its triple-quote heredoc syntax. However,
the "#" used in markdown headers is currently misinterpreted as a
comment. So, if you write this:

```elixir
@doc """
Get the first name of a user.

## Parameters

- `user` - A User struct.

## Examples

    user = %User{name: "Alice Winston"}
    User.first_name(user)
    "Alice"

"""
```

Prism interprets the markdown headers as comments, not as part of the
string, and this messes up the coloring.

04__functions__modules__and_structs___learnelixir_tv

It's easy to fix, just put the string regular expressions before the
comment regular expression in the elixir component.

### CODE REVIEW

**Comment by Golmote** [comment]
Unfortunately, this will lead to other issues (e.g. strings will be highlighted inside comments (breaking them))...
Comments might be used to comment code, and that's why we usually handle it first.

Would it be ok to only change the negative look-ahead in the comment pattern, so that we ignore comments starting with more than one hash?  `/#(?![{#]).*/`

**Comment by danielberkompas** [comment]
I'll give it a try and let you know.

**Comment by danielberkompas** [comment]
Changing the negative lookahead wasn't enough. If it was given this:

```elixir
@doc """
## Header
"""
```

It would match on `# Header`. Since Javascript doesn't support negative lookbehinds, I added a negated capture group to assert that the `#` is not preceded by any other `#`s. What do you think of this solution?

**Comment by Golmote** [comment]
Damn you're perfectly right! Please use the `lookbehind` feature provided by Prism, though, so that the char before the hash is not consumed:

```javascript
'comment': {
	pattern: /([^#])#(?![{#]).*/,
	lookbehind: true
}
```

Can you also fix the indentation before the comments you added?

I can merge this once it's done ;)

**Comment by danielberkompas** [comment]
Done! I amended the commit.

**Comment by Golmote** [comment]
Thanks!

**Comment by Golmote** [comment]
Oh, I have to add an alternative to handle the empty comment `#` and pass the tests.
The final pattern is: `/(^|[^#])#(?![{#]).*/m`

**Comment by danielberkompas** [comment]
How do you run the tests?

**Comment by Golmote** [comment]
By running `npm test`

**Comment by danielberkompas** [comment]
I'm fixing this now.

**Comment by Golmote** [comment]
It's fixed already! See ccb6566ccb14f365ab221525f09247d775a9bd06

**Comment by danielberkompas** [comment]
:+1:

**Pull request merged**
