### PR TITLE
Add .token.class-name to rest of themes

### PR DESCRIPTION
**Pull request by paladox**

### CODE REVIEW

**Comment by Golmote** [comment]
Hi, thanks for taking care of this.

I noticed the Tomorrow Night theme and the Coy theme already have the class-name handled actually, so there should be nothing to change in these files.

On the contrary, we should add support for it in the Solarized Light theme.

The change in the Okaidia theme looks good to me.

**Comment by mAAdhaTTah** [comment]
@paladox Would love to get this in. Would you be able to make the minor changes requested here?

**Comment by paladox** [comment]
Done.

**Comment by Golmote** [comment]
@mAAdhaTTah No, the changes in ` themes/prism-coy.css` and `themes/prism-tomorrow.css` need to be reverted. Those themes already handle the `class-name` token (line 149 in Coy, and 79 in Tomorrow).

**Comment by paladox** [comment]
@Golmote done.

**Comment by Golmote** [comment]
@paladox Thank you!

**Comment by paladox** [comment]
your welcome :).

**Pull request merged**
