### PR TITLE
Unicode characters in CSS properties

### PR DESCRIPTION
**Pull request by valtlai**
Highlight Unicode characters in CSS properties correctly, for example `.foo { --bär: 3 }`.

Optimized the “function” regex in the JavaScript definition: replaced `_a-zA-Z0-9` with `\w`, removed uppercase `A-Z` because the `i` flag is set.

Used that regex for CSS but removed `$` and added `-`.

### CODE REVIEW

**Comment by Golmote** [comment]
Hi! Thanks for contributing. Could you run `gulp` to generate the minified versions (and the prism.js file) please?

Also, can you update the [test file for CSS properties](https://github.com/PrismJS/prism/blob/gh-pages/tests/languages/css/property_feature.test) with an example using unicode characters, and make sure it passes? You can use `npm test` to run the tests.

**Comment by valtlai** [comment]
Do I need to install Gulp and NPM, eh?

**Comment by valtlai** [comment]
Added a test (and fixed indentation).

**Comment by Golmote** [comment]
> Do I need to install Gulp and NPM, eh?

Yes, indeed.

**Comment by valtlai** [comment]
I have not use them ever. When I have installed both do I just `cd` to the local directory and run the commands?

**Comment by Golmote** [comment]
You need to `cd` to the local directory and run `npm install`.
Once it's done, you should be able to run `gulp` and `npm test`.

**Comment by valtlai** [comment]
Added minified versions, and tests passed.

**Comment by Golmote** [comment]
Awesome thanks! Can you add the `prism.js` to the PR? It should have been modified when you ran `gulp`.

**Comment by Golmote** [comment]
Great! Looks good to me. Thanks again for contributing!

**Pull request merged**
