### PR TITLE
Updated changelog for 1.19.0

### PR DESCRIPTION
**Pull request by RunDevelopment**
(Not linkified, no date)

This also includes a small update to the changelog generation to account for `dependencies.js`.

### CODE REVIEW

**Comment by mAAdhaTTah** [comment]
I think this needs to be `1.19.0`. We're introducing new languages, which is a new feature, so minor version bump.

**Comment by mAAdhaTTah** [comment]
Set the date to today before merging.

**Comment by RunDevelopment** [comment]
Is that a request or a statement?

**Comment by RunDevelopment** [comment]
(This might sound passive aggress, but it isn't meant to.)
I intentionally publish these changelog branches in the PrismJS repository and not in my fork, so other maintainers can easily commit their own changes (maybe even using GitHub's in-browser editor). I do this because I don't want to miss a message like this causing a release to be delayed and you to be annoyed.

**Comment by mAAdhaTTah** [comment]
Hah, no worries. The thought at the time was to update the date, merge, then I'd be able to pull master & publish w/o needing to update anything, but I fell asleep before I saw this. Anyway, it's published, thanks for your help!

**Pull request merged**
