### PR TITLE
PHP: Fixed exponential runtime of a pattern

### LINKED ISSUE #2156: Endless loop with invalid PHP code
**Information:**
- Prism version: 1.18.0, latest from download page
- Plugins: none
- Environment: Browser and Node and Webpack

**Description**
Invalid PHP code leads to an endless loop when trying to highlight. Example:

~~~js
const code = "<?  \n\t// Session starten und confog.php includen  \n\tsession_start();  \n\tinclude (\"config.php\");  \n\t  \n\t// CaptchaCodes abfragen  \n\t$CAPTCHA_RandomText = \"\";  \n\tif (isset($_POST['txtCode'])){  \n\t$CAPTCHA_EnteredText = str_replace(\"<\",\"\",str_replace(\">\",\"\",str_replace(\"'\",\"\",str_replace(\"[\",\"\",str_replace(\"]\",\"\",$_POST['txtCode'])))));  \n\t}  \n\tif (isset($_SESSION['CAPTCHA_RndText'])) {  \n\t$CAPTCHA_RandomText = $_SESSION['CAPTCHA_RndText'];  \n\t}  \n  \n\t// Eingabefelder abfragen  \n\t$_SESSION['company'] = $_POST['company'];  \n\t$_SESSION['name'] = $_POST['name'];  \n\t$_SESSION['address'] = $_POST['address'];  \n\t$_SESSION['zip_code'] = $_POST['zip_code'];  \n\t$_SESSION['city'] = $_POST['city'];  \n\t$_SESSION['county'] = $_POST['county'];  \n\t$_SESSION['country'] = $_POST['country'];  \n\t$_SESSION['phone'] = $_POST['phone'];  \n\t$_SESSION['fax'] = $_POST['fax'];  \n\t$_SESSION['email'] = $_POST['email'];  \n\t$_SESSION['nachricht'] = $_POST['nachricht'];  \n\t  \n\t$email_i = $_SESSION['email'];  \n\t  \n\t// Email Funktion  \n\tfunction pruefe_mail($email_i) {  \n\t\t  if(strstr($email_i, \"@\")) {  \n\t\t\t$email_i = explode (\"@\", $email_i);  \n\t\t\tif(strstr($email_i[1], \".\")) $ok = TRUE;  \n\t\t  }  \n\t\t  return $ok;  \n\t\t}  \n\t  \n\t// Eingaben prüfen  \n\t$fehler = \"\";  \n\tif(!pruefe_mail($email_i) && !empty($email_i)) {  \n\t\t\t$fehler .= \"<li>email</li>\";  \n\t\t\t}  \n\t\t\tif ($_SESSION['name'] == \"\"){  \n\t\t\t$fehler .= \"<li>name</li>\";  \n\t\t\t}  \n\t\t\tif ($_SESSION['city'] == \"\"){  \n\t\t\t$fehler .= \"<li>city</li>\";  \n\t\t\t}  \n\t\t\tif ($_SESSION['country'] == \"\"){  \n\t\t\t$fehler .= \"<li>country</li>\";  \n\t\t\t}  \n\t\t\tif ($_SESSION['phone'] == \"\"){  \n\t\t\t$fehler .= \"<li>phone</li>\";  \n\t\t\t}  \n\t\t\tif ($_SESSION['email'] == \"\"){  \n\t\t\t$fehler .= \"<li>email</li>\";  \n\t\t\t}  \n\t\t\tif ($_SESSION['message'] == \"\"){  \n\t\t\t$fehler .= \"<li>message</li>\";  \n\t\t\t}  \n\t\t\tif ($CAPTCHA_EnteredText == $CAPTCHA_RandomText and isset($_POST['txtCode']) == true and isset($_SESSION['CAPTCHA_RndText'])){  \n\t\t\t$captcha = true;  \n\t\t\t} else {  \n\t\t\t$fehler .= \"<li>code</li>\";  \n\t\t\t}  \n\techo '<div>';\t\t  \n\tif ($fehler == \"\"){  \n\t// Email zumsammensetzen  \n\t$email = \"From: \" . $_SESSION['email'];  \n\t  \n\t  \n\t$nachrichtfertig =  \n\t\"Company: \" . $_SESSION['company'] \"n\\\"  \n\t\"Name: \" $_SESSION['name'] \"n\\\"  \n\t\"Address: \" $_SESSION['address'] \"n\\\"  \n\t\"ZIP Code: \" $_SESSION['zip_code'] \"n\\\"  \n\t\"City: \" $_SESSION['city'] \"n\\\"  \n\t\"County: \" $_SESSION['county'] \"n\\\"  \n\t\"Country: \" $_SESSION['country'] \"n\\\"  \n\t\"Phone: \" $_SESSION['phone'] \"n\\\"  \n\t\"Fax: \" $_SESSION['fax'] \"n\\\"  \n\t\"eMail: \" $_SESSION['email'] \"n\\n\\\"  \n\t\"Message: \" $_SESSION['message'];  \n\t  \n\t  \n\t$versand = mail($empfaenger, $betreff, $nachrichtfertig, $email);  \n\t\t\tif ($versand) {  \n\t\t\techo '<p class=titles>Thank you very much!</p>  \n\t\t\t\t  <p>The message were send successfully</p>';  \n\t\t\t  \n\t\t\t// Sessionvariablen löschen  \n\t\t\tunset($_SESSION['company']);  \n\t\t\tunset($_SESSION['name']);  \n\t\t\tunset($_SESSION['address']);  \n\t\t\tunset($_SESSION['zip_code']);  \n\t\t\tunset($_SESSION['city']);  \n\t\t\tunset($_SESSION['county']);  \n\t\t\tunset($_SESSION['country']);  \n\t\t\tunset($_SESSION['phone']);  \n\t\t\tunset($_SESSION['fax']);  \n\t\t\tunset($_SESSION['email']);  \n\t\t\tunset($_SESSION['nachricht']);  \n\t\t\t}  \n\t\t\t  \n\t} else {  \n\techo '<p class=titles>Error</p>';  \n\techo '<p>Please fill in all the $fehler field. <a href=\"contact.php\">back</a></p>';  \n\t}  \n\techo '</div>';\t  \n  \n\t// Session unset  \n\tunset($_SESSION['CAPTCHA_RndText']);  \n\t  \n?>\n";
const html = Prism.highlight(code, Prism.languages.php, 'php');
~~~

Example can be tested with this minimal configuration: <https://prismjs.com/download.html#themes=prism&languages=markup+clike+markup-templating+php>

**Example**

Example is attached as a ZIP file: [example.zip](https://github.com/PrismJS/prism/files/4023342/example.zip)

### PR DESCRIPTION
**Pull request by RunDevelopment**
This fixes the exponential runtime of the pattern used to identify PHP code embedded in HTML. (This resolves #2156.)

The problem was that the alternative for single-line comments `(?:\/\/|#)(?:[^?\n\r]|\?(?!>))*` was open-ended, so the regex engine could decide how many characters to match. The fix is that I added a lookahead which enforces that these comments end at either the end of a line of the end of the PHP code block.

### CODE REVIEW

**Comment by mAAdhaTTah** [comment]
Can we add a test to cover this scenario?

**Comment by RunDevelopment** [comment]
I didn't because the code is syntactically invalid which caused the exponential run time in the first place. 
So what do we want to test?

**Comment by mAAdhaTTah** [comment]
Can we add a test with the invalid code and ensure it completes? Even if the token stream is an empty array, it will still verify the bug is fixed (and not potentially reintroduced).

**Comment by RunDevelopment** [comment]
Added the test. It's parsed as an XML prolog.

**Pull request merged**
