### PR TITLE
Competition between patterns to solve the comment/string/regexp problem

### PR DESCRIPTION
**Pull request by Golmote**
This is a proposition to solve the main problem of Prism. (#307, #412, #187, #183, #155, #153...)

The PR adds the notion of competition between patterns.

Before highlighting the code, we loop through the patterns to group together the ones that are in competition with each other (each group contains what I call competitors).
Then we loop through the groups and for each part of the string, we try to match each competitor. The winner is the one which matches the closest from the start of the substring.

To indicate that some patterns are in competition, you need to add a "competition" key on the pattern, specifying an identifier for the competition. All patterns in the grammar that have the same competition identifier are in competition with each other.

If you don't change the language definitions, the behaviour is the same as before.

A behaviour that needs to be mentionned is that the position of the first competitor in the grammar determines the position all the whole competition with that identifier (i.e. all the competitors), wherever the other competitors are defined in the grammar. This should normally not be a problem, as candidates for competition are most of the time consecutives in the grammar.

I configured C-like and JS as an example, by setting the same competition key for the tokens "comment", "string" and "regexp" (that are all three "enclosing" patterns). Here is a before/after comparison :
prism-before prism-after

What do you think of it ?

### CODE REVIEW

**Comment by Golmote** [comment]
Hi there!

I thought a lot about this stuff during the holidays. Your suggestion using `start` and `end` patterns would raise some tricky problems...
To match the whole symbol, we'd need to merge the `start`, `contents` and `end` regexps together, leading to the same problems encountered in PR #444! What happens if the user sets the `i` modifier only on the `start` token, for example?

What do you think? Can we sort it out or should we go back to the boolean solution, and just find a better name than `competition`?

**Comment by zeitgeist87** [comment]
You don't have to combine them. You search for `start` and get an index, then you search for `end` and get an index, then you check if `contents` matches inbetween. If it's possible, you combine them of course.

**Comment by zeitgeist87** [comment]
You could even optimize a bit, by matching only `start` for tokens that are in competition. Then sort the resulting list of start indices in decending order. Then go through the list and match `end` and `contents`. The first match is the new token.

**Comment by Golmote** [comment]
This looked like an awesome idea until I tested strings like `"foo \" bar"`. When searching for `end`, we find the escaped quote.
Even if we add some lookbehind check to ensure the quote is not escaped, it will fail on `"foo \\"` by thinking the quote is escaped when it's not...

So we might need to consume `contents` before searching for `end`, but this would require `contents` to be more precise. Like `/(\\.|[^"])*/` instead of just `/(\\?.)*/` for strings, for example. This is probably not easy enough for "a random dev, new to Prism, trying to hack together a language definition".

What do you think?

**Comment by zeitgeist87** [comment]
@Golmote yes you are absolutely right. I hadn't thought of escaped end patterns. You could also not use back references to refer to the string that was matched with `start`.

A `boolean` flag `competition` would probably be best, although I like your idea of allowing different scopes of competition by nameing them with a string.

**Comment by LeaVerou** [comment]
@Golmote: If the dev gives us the escape character too (which would default to `\`, but other languages may have different escape characters), can’t we build the necessary regex ourselves in the background?

I really think the flag idea is confusing for devs trying to hack together language definitions. Prism’s priorities are: 1. API & code simplicity 2. Performance 3. Small code size, in that order.

Also, have we done any performance comparison between this compared to previous versions of Prism that failed on such nested structures? A small performance hit is acceptable, but if Prism has to become e.g. 4 times slower to become a bit more correct, it wouldn't be worth it. It's a tradeoff.

**Comment by Golmote** [comment]
I just ran a quick benchmark on the three concerned versions of Prism: the original (current state on Prism website), the one from this PR (in the current state) and the one from PR #444 (at commit zeitgeist87/prism@0187761a56d8abdc83288921e4c4782ecbab955d).

I did not benchmark your proposed API as I could not yet make it work properly.

The benchmark highlights the following code:
 ```javascript
/*fo"/o*/ "*/bar", /ba"z*/;
"Foo // bar"
"/foo/"; /* "bar" /baz/ */
/"foo"/, "/*bar", "baz*/";
/foo"/, "bar", "baz";
// foo "bar" baz
"foo /* bar */ baz";
```

I repeated this code fragment multiple times to test for longer codes.

The code was highlighted a first time before the benchmark runs so that I could check the result and ignore the grammar optimization time in PR #444.

Here are the results in Chrome 39.0.2171.95:

Prism version | Code length | Number of runs | Average time
---|---|---|---
Original | 155 chars | 1000 | 0.29 ms
PR #424 | 155 chars | 1000 | 0.37 ms (27% slower)
PR #444 | 155 chars | 1000 | 0.35 ms (20% slower)
Original | 1550 chars | 100 | 1.86 ms
PR #424 | 1550 chars | 100 | 2.64 ms (41% slower)
PR #444 | 1550 chars | 100 | 2.38 ms (28% slower)
Original | 15500 chars | 50 | 9.99 ms
PR #424 | 15500 chars | 50 | 14.28 ms (43% slower)
PR #444 | 15500 chars | 50 | 13.67 ms (37% slower)
Original | 155000 chars | 10 | 171.87 ms
PR #424 | 155000 chars | 10 | 208.23 ms (21% slower)
PR #444 | 155000 chars | 10 | 200.53 ms (17% slower)

Here are the results in Firefox 34.0.5:

Prism version | Code length | Number of runs | Average time
---|---|---|---
Original | 155 chars | 1000 | 1.11 ms
PR #424 | 155 chars | 1000 | 1.46 ms (31% slower)
PR #444 | 155 chars | 1000 | 1.39 ms (25% slower)
Original | 1550 chars | 100 | 5.53 ms
PR #424 | 1550 chars | 100 | 7.08 ms (28% slower)
PR #444 | 1550 chars | 100 | 7.12 ms (28% slower)
Original | 15500 chars | 50 | 51.35 ms
PR #424 | 15500 chars | 50 | 74.60 ms (45% slower)
PR #444 | 15500 chars | 50 | 69.39 ms (35% slower)
Original | 155000 chars | 10 | 1022.95 ms
PR #424 | 155000 chars | 10 | 1705.92 ms (66% slower)
PR #444 | 155000 chars | 10 | 2153.13 ms (110% slower)

Finally, here is the benchmark code I used:

```html
<pre><code id="benchmark-core" class="language-javascript">/*fo"/o*/ "*/bar", /ba"z*/;
"Foo // bar"
"/foo/"; /* "bar" /baz/ */
/"foo"/, "/*bar", "baz*/";
/foo"/, "bar", "baz";
// foo "bar" baz
"foo /* bar */ baz";
</code></pre>

<script src="components/prism-core.js"></script>
<script src="components/prism-clike.js"></script>
<script src="components/prism-javascript.js"></script>
<script>
	(function() {
		var elt = document.getElementById('benchmark-core'),
			code = elt.textContent;

		Prism.highlightElement(elt);

		function avg(arr) {
			return arr.reduce(function(a,b) { return a+b; })/arr.length;
		}
		function str_repeat(s, n) {
			var res = '';
			while(n--) {
				res += s;
			}
			return res;
		}

		function benchmark(code, cpt, cb) {
			var logs = [],
				f = function() {
					if(cpt--) {
						var start = performance.now();
						Prism.highlight(code, Prism.languages.javascript, 'javascript');
						logs.push(performance.now() - start);
						requestAnimationFrame(f);
					} else {
						console.log('Average time: ' + avg(logs) + ' ms');
						cb && cb();
					}
				};
			console.log('Highlighting '+code.length+'-char code '+cpt+' times.');
			f();
		}

		window.onload = function() {
			benchmark(code, 1000, function () {
				benchmark(str_repeat(code, 10), 100, function () {
					benchmark(str_repeat(code, 100), 50, function () {
						benchmark(str_repeat(code, 1000), 10, function () {
							console.log('Done');
						});
					});
				});
			});
		};
	}());
</script>
```

**Comment by zeitgeist87** [comment]
@Golmote Thanks for the performance tests. Really nice work!

**Comment by Golmote** [comment]
> @Golmote: If the dev gives us the escape character too (which would default to \, but other languages may have different escape characters), can’t we build the necessary regex ourselves in the background?

@LeaVerou If we need to build the regexp by combining the `start`, `content` and `end` patterns, with or without any escape character, we will encouter the same problems with the regexp flags (see previously https://github.com/LeaVerou/prism/pull/424#issuecomment-68592959, or yours here https://github.com/LeaVerou/prism/pull/444#issuecomment-67894079)

If we try to add the escape character to zeitgeist87's suggestion (https://github.com/LeaVerou/prism/pull/424#issuecomment-68594600), we could indeed ensure the `start` and `end` pattern are not preceded by the escaped character, but it would fail on cases like `"foo \\"`.

Another idea, to ease the merging of the different parts, we could ask the dev to input "regexp-strings" instead of real regexps so that don't have any flag problems. For example, the C-like string pattern would become something like `{start: '("|\')', contents: '(\\\\?.)*?', end: '\\1'}`. But IMO, all these backslashes are quite ugly, and the whole thing is really easy to get.

Finally, as the C-like string pattern shows it, there is the problem of the back references, which are particularly needed for patterns that allow any identifier to be used as a delimiter (e.g Heredoc strings in PHP:
```php
$str = <<<PRISM_IS_GREAT
Example of string
spanning multiple lines
using heredoc syntax.
PRISM_IS_GREAT;
```
This needs back references, to be matched properly.)

**Comment by Golmote** [comment]
I'm still trying to think about a better word for an hypothetical boolean flag but I'm quite stuck with my lack of english vocabulary. Maybe something like `matchFirst` would be more appropriate?

Also remember that not setting the boolean flag would just keep the current behaviour of Prism and devs will write new language definitions by looking at the existing ones so I guess they will quickly understand what the boolean is meant for...

**Comment by LeaVerou** [comment]
Wow, @Golmote you never cease to impress!! Nice work!!

**Comment by zeitgeist87** [comment]
I kind of like the name `greedy` for the flag.

**Comment by Golmote** [comment]
Wouldn't `greedy` be confusing regarding its meaning when talking about regexps?

**Comment by zeitgeist87** [comment]
@Golmote I think `greedy` is a good choice, because it has essentially the same meaning as in the context of a regex, but on the scope of the whole language. So people who know what geediness means for regexes can intuitively understand what it means on a larger scale. But maybe I am wrong. I am awful at nameing things...

**Comment by Golmote** [comment]
>  I am awful at nameing things...
Haha! So I am.

Well, if we stay with the flag solution, maybe @LeaVerou would have a better idea for the name.

**Pull request closed without merging**
