### PR TITLE
Added support for BBCode

### LINKED ISSUE #2086: Language Request: BBCode
**Language**

BBCode is a markup language used in forum posts.

**Additional resources**

https://en.wikipedia.org/wiki/BBCode

### PR DESCRIPTION
**Pull request by RunDevelopment**
This resolves #2086.

I used Pygments' [BBCode definition](https://bitbucket.org/birkenfeld/pygments-main/src/19eebedfaad41803086b4f7224f1e6bd19a1ab51/pygments/lexers/markup.py#lines-30) for reference (because it's WikiMedia's syntax highlighter) but in the end the whole definition is just a modified version of Prism markup's `tag` pattern.

### Screenshot

image

### CODE REVIEW

**Comment by mAAdhaTTah** [comment]
Actually, do we need an example html page for this language?

**Comment by RunDevelopment** [comment]
Ahh, yes. I forgot.

**Comment by RunDevelopment** [comment]
Should I make of PR which adds this into `npx gulp premerge`, so Travis can pick up on this?

**Comment by mAAdhaTTah** [comment]
I was going to suggest a PR template, but a gulp method to check all the languages have examples could be helpful too.

**Comment by RunDevelopment** [comment]
I just wanna see the ~world burn~ build fail.

A PR template is also a good idea, so you can know why the build failed.

**Pull request merged**
