### PR TITLE
Better minify

### PR DESCRIPTION
**Pull request by RunDevelopment**
This changes the options passed to Uglify to better minify our files. Changes:

1. More compress passes. I increased the number of compress passes from 1 (default) to 10.
1. I allowed Uglify to rename all properties with names that match `/^\$\w+$/` and renamed a few properties in core. This saves about 200 bytes uncompressed.

I would really like to see what our bundle size bot has to say about this.

---

Because Uglify does more compress passes, the build time increased by 50%.

<details>

Before
```
[18:25:02] Using gulpfile ~\Git\prism\gulpfile.js
[18:25:02] Starting 'default'...
[18:25:02] Starting 'minifyComponents'...
[18:25:02] Starting 'componentsJsonToJs'...
[18:25:02] Starting 'build'...
[18:25:02] Starting 'languagePlugins'...
[18:25:02] Finished 'componentsJsonToJs' after 164 ms
[18:25:02] Finished 'languagePlugins' after 196 ms
[18:25:02] Starting 'minifyPlugins'...
[18:25:02] Finished 'build' after 410 ms
[18:25:03] Finished 'minifyPlugins' after 829 ms
[18:25:04] Finished 'minifyComponents' after 1.86 s
[18:25:04] Starting 'docsClean'...
[18:25:04] Finished 'docsClean' after 11 ms
[18:25:04] Starting 'docsCreate'...
[18:25:05] Documented 2 files!
[18:25:05] Finished 'docsCreate' after 901 ms
[18:25:05] Starting 'docsRemoveExcessFiles'...
[18:25:05] Finished 'docsRemoveExcessFiles' after 4.96 ms
[18:25:05] Starting 'docsAddFavicon'...
[18:25:05] Finished 'docsAddFavicon' after 39 ms
[18:25:05] Starting 'docsFixLineEnds'...
[18:25:05] Finished 'docsFixLineEnds' after 11 ms
[18:25:05] Finished 'default' after 3.04 s
```

After
```
[18:24:04] Using gulpfile ~\Git\prism\gulpfile.js
[18:24:04] Starting 'default'...
[18:24:04] Starting 'minifyComponents'...        
[18:24:04] Starting 'componentsJsonToJs'...      
[18:24:04] Starting 'build'...
[18:24:04] Starting 'languagePlugins'...
[18:24:04] Finished 'componentsJsonToJs' after 173 ms
[18:24:04] Finished 'languagePlugins' after 214 ms
[18:24:04] Starting 'minifyPlugins'...
[18:24:04] Finished 'build' after 551 ms
[18:24:06] Finished 'minifyPlugins' after 1.4 s
[18:24:07] Finished 'minifyComponents' after 3.09 s
[18:24:07] Starting 'docsClean'...
[18:24:07] Finished 'docsClean' after 7.9 ms       
[18:24:07] Starting 'docsCreate'...
[18:24:08] Documented 2 files!
[18:24:08] Finished 'docsCreate' after 991 ms
[18:24:08] Starting 'docsRemoveExcessFiles'...
[18:24:08] Finished 'docsRemoveExcessFiles' after 48 ms
[18:24:08] Starting 'docsAddFavicon'...
[18:24:08] Finished 'docsAddFavicon' after 55 ms
[18:24:08] Starting 'docsFixLineEnds'...
[18:24:08] Finished 'docsFixLineEnds' after 118 ms
[18:24:08] Finished 'default' after 4.4 s
```

</details>

### CODE REVIEW

**Comment by RunDevelopment** [comment]
@mAAdhaTTah Danger doesn't add its message. This is a new PR after I couldn't get the message to appear in #2620.

**Review by mAAdhaTTah — APPROVED** [review]
I'm open to this cuz all of the property mangling is internal data structures & functions. Just gotta be _really_ careful with the `$` property prefixing if we add to anywhere else.

**Comment by RunDevelopment** [comment]
Those file size changes are very disappointing. I only ever checked the uncompressed files and it seems like gzip does a really good job at compressing our minified files anyway. I don't think this PR is worth the added complexity and build time cost. I'll close this now.

Good thing we have the bot.

**Comment by joshgoebel** [comment]
> seems like gzip does a really good job at compressing our minified files anyway.

That's been my experience also.  gzip covers a LOT of sins... hacking on the source (or minification) to reduce the size is very much as uphill battle unless you're just removing huge swaths of code or long lists of things, etc.

**Comment by mAAdhaTTah** [comment]
Some of them even went up in size, which I find fascinating.

**Pull request closed without merging**
