### PR TITLE
CSS: Highlight attribute selector

### PR DESCRIPTION
**Pull request by RunDevelopment**
This PR adds additional highlighting for attribute selectors.

Spec: [CSS 3](https://drafts.csswg.org/selectors-3/#attribute-selectors), [CSS 4](https://drafts.csswg.org/selectors-4/#attribute-selectors)

### Example

image

### CODE REVIEW

**Comment by RunDevelopment** [comment]
Are you ok with this @LeaVerou ? I'm asking because of your comment [here](https://github.com/PrismJS/prism/pull/375#issuecomment-57237888).
(Same for #1650)

**Comment by LeaVerou** [comment]
If the others are ok with it!

**Comment by RunDevelopment** [comment]
Since [people seem to be interested](https://github.com/PrismJS/prism/issues/1623#issuecomment-463428551) in this feature, I'm going to merge this if @mAAdhaTTah gives his OK.

**Comment by mAAdhaTTah** [comment]
LGTM!

**Comment by atomiks** [comment]
How do I use CSS extras? Is it documented somewhere?

**Comment by RunDevelopment** [comment]
You load both languages and CSS Extras will add new features to CSS, so you just use the normal `language-css` class.

**Comment by atomiks** [comment]
I'm using a plugin for this which indirectly loads them for me, is the name `language-css-extras`?

**Comment by RunDevelopment** [comment]
Are you using the [Autoloader](https://prismjs.com/plugins/autoloader/)?

**Comment by atomiks** [comment]
It's a gatsby plugin, here's the source: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-prismjs/src/load-prism-language.js

**Comment by RunDevelopment** [comment]
That seems to be a problem with the library. Seems like they don't support [loading language extensions](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-prismjs/src/highlight-code.js).
It would probably be best to open an issue over there.

**Pull request merged**
