### PR TITLE
Add tests for git

### PR DESCRIPTION
**Pull request by Golmote**

### CODE REVIEW

**Comment by LeaVerou** [comment]
Golmote, in the spirit that some tests are better than no tests, feel free to merge all the tests PRs. Thanks so much!!

**Comment by Golmote** [comment]
Yes, I started to merge the first ones this morning. This one will be merged tomorrow.

**Comment by Golmote** [comment]
I'm intentionally leaving them pending for a week, so that they can be reviewed. That's the whole point of a PR right? Otherwise I would just commit directly. ^^

**Comment by Golmote** [comment]
It's been 7 days. According to what I said in #680, I'm merging this.

**Pull request merged**
