### PR TITLE
JS Extras: Highlight import and export bindings

### PR DESCRIPTION
**Pull request by RunDevelopment**
This wraps the binding declarations of import/export statements.

---

@karlhorky
This should also work for you, right?

image

### CODE REVIEW

**Comment by karlhorky** [comment]
LGTM, thanks!

**Review by karlhorky — APPROVED** [review]

**Comment by mAAdhaTTah** [comment]
`maybe-class-name` seems a bit odd to me. What's the idea here?

**Comment by karlhorky** [comment]
I think that's not new - looks like it was added in https://github.com/PrismJS/prism/pull/1743

**Comment by RunDevelopment** [comment]
Yes, it's been there for a while. The idea is that class names are usually written in pascal case, so we can use this naming convention. However, it's not perfect, so I didn't want to name it "class-name".

**Comment by mAAdhaTTah** [comment]
Thanks for the clarification!

**Comment by karlhorky** [comment]
@RunDevelopment @mAAdhaTTah could we have this also published as a new version of `prismjs`?

Version `1.21.0` (current version as of 8 Oct 2020) doesn't include this change: https://unpkg.com/browse/prismjs@1.21.0/components/prism-js-extras.js

**Comment by RunDevelopment** [comment]
Well, it's been 2 months since the last release.

@mAAdhaTTah I'll prepare the changelog.

**Comment by mAAdhaTTah** [comment]
@karlhorky @RunDevelopment v1.22.0 has been published.

**Comment by RunDevelopment** [comment]
@mAAdhaTTah Thanks! 

On that note: Should we include all changes in the GH release notes? I always removed/didn't include them because I don't want to maintain two copies of the same thing. How do we want to handle this going forward? Always/never include the changes or just have a link to our changelog in the release notes?

**Comment by mAAdhaTTah** [comment]
@RunDevelopment That makes sense, just do it in the Changelog.

**Comment by karlhorky** [comment]
Cool, thanks for that!

**Pull request merged**
