### PR TITLE
C/C++: Improved macros and expressions

### PR DESCRIPTION
**Pull request by RunDevelopment**
This can be seen as an extension of #2320.

Macro expressions after the directive are now highlighted. I also added some highlighting for macro-specific syntaxes like `\` at line ends and the concatenation operator.

### CODE REVIEW

**Comment by blotfi** [comment]
when could I download the prismjs that include this #2440 enhancement?

**Comment by RunDevelopment** [comment]
@blotfi Right now!

**Comment by blotfi** [comment]
just to be more precise, it must be valid in **C language** (and therefore in C++ language) #2440 enhancement
thanks

**Comment by blotfi** [comment]
> @blotfi Right now!

you mean if i download
https://prismjs.com/download.html#themes=prism&languages=clike+c+cpp+json&plugins=line-numbers+file-highlight+keep-markup

I will find the modification (for C and CPP) ?

**Comment by RunDevelopment** [comment]
> you mean if i download [...] I will find the modification (for C and CPP) ?

Yes.

> it must be valid in C language

Macro expressions will be highlighted as C code in C and as C++ code in C++. You can see this with `#define` macros that contain C++ keywords.

C:
image

C++:
image

Is that what you meant?

**Comment by blotfi** [comment]
I am testing now, 2 min
I see you put:

			'directive-hash': /^#/,
			'punctuation': /##|\\(?=[\r\n])/,
			'expression': {
				pattern: /\S[\s\S]*/,
				inside: Prism.languages.c

**Comment by blotfi** [comment]
Works great
Thanks

I will open another issue for `#include <xc.h>`
it works well with file 
`<pre data-src="code/TP0/cmde.c"></pre>`
but not if it is included in the html

```
<pre data-start="0" ><code class="language-cpp line-numbers">
#include <xc.h>
return;
#ifdef NON
void list()
{
}

```


image

**Pull request merged**
