### PR TITLE
docs: add gitter badge in README

### PR DESCRIPTION
**Pull request by ersachin3112**
Add glitter badge in readme as suggested in https://github.com/PrismJS/prism/issues/309#issuecomment-50861379

### CODE REVIEW

**Comment by RunDevelopment** [comment]
Thank you for the PR @ersachin3112!

However, I'm not sure whether we still use gitter... There is also the Github discussion tab which (while not enable in this repo) seems to have a similar purpose but __a lot__ more structured.

I would like to know what the other maintainers think. 
@LeaVerou @mAAdhaTTah @Golmote

Personally, I'd rather enable the GH discussion tab instead of reviewing gitter.

**Comment by mAAdhaTTah** [comment]
Yeah, I agree. Gitter has been quiet since 2018 and I would prefer to not have to install another chat app. GitHub discussions would be good, if we think it's needed.

**Comment by LeaVerou** [comment]
I thought Github Discussions were more forum than chat? Anyhow, I'm fine with whatever you decide!

Another option could be a Slack channel.

**Comment by RunDevelopment** [comment]
> I thought Github Discussions were more forum than chat

Good point. Yes, it's not a perfect replacement but I think that something forum-like would be better. 

Many of the issues we currently get are in this Q&A form. Opening a GH discussions tab could lead to people asking their questions over there instead of opening an issue. This would neatly separate actual issues from questions.

What do you think? Want to give GitHub discussions a try? If it doesn't work out, we can just close it again.

**Comment by LeaVerou** [comment]
Nothing to lose by giving it a try!

**Comment by ersachin3112** [comment]
Yeah, Enabling GitHub discussion sounds good

**Comment by RunDevelopment** [comment]
I enabled the discussions tab. I also added a link to our issue templates, so people can more easily find it.

image

---

Since we now have GitHub Discussions, I will close this PR for now. Feel free to ask to reopen this if gitter is still needed or if we closed GitHub Discussions.

**Pull request closed without merging**
