### PR TITLE
Fix ReDoS

### PR DESCRIPTION
**Pull request by ready-research**
Fix ReDoS

### CODE REVIEW

**Comment by RunDevelopment** [comment]
`components/prism-markup.min.js` has a new line at the end for some reason. That's why the build fails.

**Comment by ready-research** [comment]
@RunDevelopment Is it okay now? 
Please validate the huntr link by clicking on `mark as valid`, and also you can `confirm the fix`. Thank you.

**Comment by RunDevelopment** [comment]
@ready-research That new line is still present. Your last commit was empty.

**Comment by ready-research** [comment]
@RunDevelopment I am not seeing any new line in `components/prism-markup.min.js`. Can you please edit that if you have permission to do that? Or feel free to raise a new pull to resolve this issue. Thank you.

**Comment by ready-research** [comment]
@RunDevelopment Can you please `confirm the fix` in [huntr](https://www.huntr.dev/bounties/8c16ab31-6eb6-46d1-b9a4-387222fe1b8a/)?

**Comment by RunDevelopment** [comment]
Done :)

**Pull request merged**
