### PR TITLE
Better class name detection

### PR DESCRIPTION
**Pull request by RunDevelopment**
This PR improves the regexes used to detect CSS class names.

I looked through all plugins, so that should be all of the over-accepting regexes.

---

Thank you @ExE-Boss for bringing [this issue](https://github.com/mozilla/kuma/pull/5275) to my attention.

### CODE REVIEW

**Comment by ExE-Boss** [comment]
It might be a good idea to add tests for this.

**Comment by RunDevelopment** [comment]
Tests would require a virtual DOM, which we don't have right now. So no tests for now.

**Comment by ExE-Boss** [comment]
You could probably use [JSDOM](https://github.com/jsdom/jsdom) [(on&nbsp;npm)](https://www.npmjs.com/package/jsdom) for&nbsp;that, but&nbsp;that’s&nbsp;probably for&nbsp;a&nbsp;separate&nbsp;PR.

**Comment by RunDevelopment** [comment]
#1646

**Pull request merged**
