### PR TITLE
Do not highlight CSP directive names with adjacent hyphens

### LINKED ISSUE #2661: CSP directive names with adjacent hyphens are highlighted
**Information**

- Language: CSP
- Plugins: none

**Does the problem still occur in the latest version of Prism?**

[Yes](https://prismjs.com/test.html#language=csp).

**Description**

Directive names with adjacent hyphens are highlighted. For example, Prism highlights `default-src` inside the following sequences:

```
fake-default-src 'none'
default-src-is-a-fake 'none'
```

The error is caused by `\b`. The first `\b` has been [there](https://github.com/PrismJS/prism/blob/dfa5498a0b507c429c49eed4c415f5275decfa53/components/prism-csp.js#L14) from the beginning. Then I [added](https://github.com/PrismJS/prism/blob/537a9e8015c28d516c1eb2ab8cd2aa82c2d2e32c/components/prism-csp.js#L14) the last `\b`. Both of them are erroneous, because `\b` uses `[0-9A-Z_a-z]` (see ECMA-262, sections [21.2.1](https://tc39.es/ecma262/2020/#sec-patterns), [21.2.2.12](https://tc39.es/ecma262/2020/#sec-characterclassescape), [21.2.2.6.1](https://tc39.es/ecma262/2020/#sec-runtime-semantics-wordcharacters-abstract-operation)), whereas directive names consist of `[-0-9A-Za-z]` (see [CSP 1.0](https://www.w3.org/TR/2012/CR-CSP-20121115/#policies), [CSP 1.1](https://www.w3.org/TR/2014/WD-CSP11-20140211/#policies), [CSP2](https://www.w3.org/TR/2016/REC-CSP2-20161215/#directive_name), and [CSP3](https://www.w3.org/TR/2018/WD-CSP3-20181015/#grammardef-directive-name)).

**Code snippet**

<details>

<summary>The code being highlighted incorrectly.</summary>

```
fake-default-src 'none'
default-src-is-a-fake 'none'
```

The `default-src` part should not be highlighted.

</details>

### PR DESCRIPTION
**Pull request by edukisto**
Resolves #2661.

### CODE REVIEW

**Review by RunDevelopment — CHANGES_REQUESTED** [review]
Very good work @edukisto!

Please add a [test case](https://prismjs.com/test-suite.html#writing-tests-creating-your-test-case-file) for your issue. Language definition is good as is.

**Comment by edukisto** [comment]
Is the name of the file correct? I mean `issue2661.test`.

**Comment by RunDevelopment** [comment]
Yes it is.

**Review by RunDevelopment — APPROVED** [review]

**Comment by RunDevelopment** [comment]
Thank you for contributing @edukisto!

**Comment by edukisto** [comment]
Thank you, @RunDevelopment!

**Pull request merged**
