### PR TITLE
Added resource to template for quickstart

### PR DESCRIPTION
**Pull request by javatlacati**
Hope this can boost the number of languages supported.

### CODE REVIEW

**Comment by Golmote** [comment]
I'm not sure about this. The pens you provide (why are they hosted on two different websites, BTW? oO) aren't really helpful...

I guess we could host a grammar template in the repo, but I don't really see the point, since there are lots of components already available to get inspired!

**Comment by javatlacati** [comment]
Just not to favore one site, even if my favorite if plkr.
Well... I've checked some running examples and most of them fail because user's don't know how to integrate into code the functionality.
For example [this] (http://jsfiddle.net/PeterChaplin/ta9vy1e0/), or [this](http://stackoverflow.com/questions/18391425/markup-not-showing-up-using-prism-js), or this [one](http://codepen.io/chriscoyier/pen/cGhpf).

**Comment by Golmote** [comment]
Your first example mostly fails because the included files ([[1]](https://dl.dropboxusercontent.com/u/313630820/js/prism.js/prism.js), [[2]](https://dl.dropboxusercontent.com/u/313630820/js/prism.js/prism.css)) do not exist...
Your third example works fine too, once you fix the wrong stylesheet URL.

For your second example... well, we can't do much about the JSFiddle issue. And regarding the fact that `<pre>` tags interpret HTML, as I already explained in #639, this is its normal behaviour, and Prism does not change anything to it. To display an HTML tag inside a `<pre>`, you *must* escape the "less-than" character as `&lt;`.

**Comment by javatlacati** [comment]
I know, but I didn't created the examples as you may nottice. If people are making mistakes is because of a lack of a template they can easily reach trough google search. JSFiddle and codepen excels in ease to find in google search because of their tag functionality meanwhile github doesn't.
I know I don't have the best example ever made, if you can improve it we'll be pleased.
I consider that the repo needs more than a template a running example that we can modify and get the output instantly without the need to download and configure it locally as you can achieve with those kind of sites.
Those sites have also the advantage of being social aware, because they integrate social network & sharing functionalities, and many people use them as portfolio when getting some job, so.. they're serious and high audience with a huge community wiling to learn and share each one.

**Comment by Golmote** [comment]
I get your point. I'll let @LeaVerou decide whether she wants to merge this.
Thanks for contributing, anyway.

**Comment by mAAdhaTTah** [comment]
I don't think this is necessary, tbh. Appreciate the contribution, but going to close.

**Comment by LeaVerou** [comment]
Also, why on earth does that codepen have the whole Prism code pasted in? Why not just add it as a resource from the CDN and get updates as they are released?
Yeah, I second @mAAdhaTTah’s decision.

**Pull request closed without merging**
