### PR TITLE
Markdown: Added support for nested bold and italic tokens

### LINKED ISSUE #1849: Markdown: Too greedy italic punctuation
**Information**
- Language: Markdown
- Plugins: none

**Description**
The punctuation of italic text with `*` and `_` will match any number of leading `*`s and `_`s.

Scratch and bold have similar issues.

**Code snippet**

```markdown
*__foo__* or _**bar**_
```

image

---

I want to mention that this bug is trivial to fix using #1679.
Possible solution:

```js
// Allow only one line break
pattern: /(^|[^\\])([*_])((?:(?:\r?\n|\r)(?!\r?\n|\r)|.)+?)(\2)/,
lookbehind: true,
greedy: true,
groups: {
	$2: 'punctuation',
	$4: 'punctuation',
}
```

Support for nested styles could be added with `$3: Prism.languages.markdown`.

### PR DESCRIPTION
**Pull request by RunDevelopment**
This PR adds support for nested bold and italic tokens.

This also resolves #1849.

<details>
<summary><strong>Example</strong></summary>

Before:
image

After:
image

</details>

### CODE REVIEW

**Comment by RunDevelopment** [comment]
@DaveJarvis Thank you for taking the time to review this PR!

> bold and italic share nearly identical regular expressions
>bold, italic, and strike share nearly the same content

The new `createInline` function should address both issues.

>pandoc's markdown defines ::: as well, for classes
>pandoc's markdown supports { } after various elements, also for classes

I don't think we need to support a parser specific feature. If it's a commonly used feature, then sure we'll add it.
But you might want to open a new issue for this or add it to #1558 as this isn't within the scope of this PR.

>not immediately obvious why token.content[2] isn't used/defined (line 196)

I added a comment explaining the structure of `token.content`.

>don't see any tests for ** bold with _ italic inside
>don't see any tests for __ bold with * italic inside

Added.

> is bold/italic/strike a possibility?

Yes, you can nest bold, italic, and strike, or is there any issue with it?
The reason why support for nested bold, italic tokens was so difficult is that they can use the same character as delimiters. This makes parsing very hard and error-prone (sometimes even actual MD parser get wrong). Because strikes use a different character, there shouldn't be an issue, or is there?

**Comment by DaveJarvis** [comment]
>  If it's a commonly used feature, then sure we'll add it.

Available since Oct 2017 (https://github.com/jgm/pandoc/issues/168), so it's gaining in usage and popularity.

> Yes, you can nest bold, italic, and strike, or is there any issue with it?

I didn't see any specific unit tests that go through all the combinations, but maybe they aren't necessary.

**Comment by RunDevelopment** [comment]
Because strike uses different delimiters than bold and italic, so it's generally less problematic. So I think that [this](https://github.com/PrismJS/prism/blob/84b9651b29b17e94c0d5f672c7291d288deb9248/tests/languages/markdown/strike_feature.test) should be sufficent testing.

**Comment by RunDevelopment** [comment]
Regarding the combinations: Yes we could write such a function but I don't think we have to. Looking at the regular expression, it's enough to test the nested tokens one level deep (It doesn't make sense the nest e.g. bold inside bold which makes things simpler) which gives us 6 * 4 combinations which are all covered by the bold, italic and strike tests in this PR.
More extensive tests might be necessary in the future but for now, I think it's fine as is.

**Comment by RunDevelopment** [comment]
@DaveJarvis Again, thank you for reviewing!

**Pull request merged**
