### PR TITLE
Remove the icon from README.md

### LINKED ISSUE #2669: A broken icon link in README.md
**Information:**

- Prism version: 1.16–1.22
- Plugins: none
- Environment: browser

**Description**

The icon link (<del>http://awesomes.oss-cn-beijing.aliyuncs.com/readme.png</del>) has been broken for months. The text we see (中文说明) is the `alt` attribute’s value. See https://github.com/PrismJS/prism/blame/9f82de508dab4944e0b11524fe95f07beaa5b83f/README.md#L32

**Example**

https://web.archive.org/web/20201112010612/https://github.com/PrismJS/prism

### PR DESCRIPTION
**Pull request by edukisto**
Resolves #2669.

### CODE REVIEW

**Comment by RunDevelopment** [comment]
Thank you for the fix @edukisto!

We should probably change the text thou

image

I checked using [this tool](https://www.chineseconverter.com/en/convert/find-out-if-simplified-or-traditional-chinese) whether the translation is in [traditional Chinese or simplified Chinese](https://en.wikipedia.org/wiki/Chinese_language)and it came back as simplified Chinese. So I think we should replace the text with a simple "简体中文". Chinese readers will understand.

**Comment by edukisto** [comment]
Aha, I see, 简体中文 means “Simplified Chinese”. It can be found on [Wikipedia](https://zh.wikipedia.org/wiki/%E7%AE%80%E5%8C%96%E5%AD%97#-{zh-cn:%E8%AE%A1%E7%AE%97%E6%9C%BA;zh-tw:%E9%9B%BB%E8%85%A6;}-%E7%B7%A8%E7%A2%BC).

**Comment by RunDevelopment** [comment]
Oh, I forgot mention this... Sorry.

**Comment by RunDevelopment** [comment]
Thank you for contributing @edukisto!

**Comment by edukisto** [comment]
Thank you, @RunDevelopment!

**Pull request merged**
