### PR TITLE
remove extra space before language class

### PR DESCRIPTION
**Pull request by Sibiraj-S**
remove additional space before adding append language to the element.

### CODE REVIEW

**Comment by Golmote** [comment]
Currently, you can use Prism this way:
```html
<div class="language-markup">
    <pre class="foobar"><code>&lt;div></code></pre>
</div>
```
When Prism runs, the class `language-markup` will be added on the `<pre>` tag.

I'm pretty sure your change would break this behaviour, and set the class to `foobarlanguage-markup` instead of `foobar language-markup`.

**Comment by LeaVerou** [comment]
Yup, @Golmote is right, sorry!

**Comment by Sibiraj-S** [comment]
No @Golmote. I made this PR because there is an extra space . let me attach the screen shot too

it is appending like this. and I checked that too 

```
<div class=" language-markup">
    <pre class="foobar"><code>&lt;div></code></pre>
</div>
```

**Comment by Sibiraj-S** [comment]
This is a plunker I showing it to test http://embed.plnkr.co/F77rcio6e4Cj5T0Pk2w3/

screen shot 2017-07-12 at 11 06 38 am

I marked the extra space. ie., actually three spaces between class

untitled

**Comment by Golmote** [comment]
I checked again this morning. In many other use cases, the extra space is perfectly useless and it would be fine to remove it. But I confirm your PR prevents Prism from properly adding a class when there is already a class on the `<pre>` or `<code>` tag, and breaks the example I gave previously.

**Comment by Sibiraj-S** [comment]
yeah. i checked to my PR breaks the code.

**Comment by Sibiraj-S** [comment]
@Golmote . I heard that having extra space may cause problems during the class string manipulations

**Comment by kylekatarnls** [comment]
It would not be the responsibility of Prism but of the library that manipulate the class string. HTML coder should be able to write this freely:
```
<p class="
  foo
  bar
"></p>
```
Every browser will understand this properly for getElementByClassName API or for CSS.

So libraries too could be free to add spaces anywhere in classes if it helps.

**Comment by LeaVerou** [comment]
> I heard that having extra space may cause problems during the class string manipulations

Only for extremely sloppy code. @kylekatarnls is right.

**Pull request closed without merging**
