### PR TITLE
Added prism.scss

### PR DESCRIPTION
**Pull request by sivankanat**
added prism.scss for imports

### CODE REVIEW

**Comment by RunDevelopment** [comment]
@sivankanat Please explain your motivation and the changes of this PR in more detail.

@mAAdhaTTah What do you think about this? SASS/SCSS was discussed in #1055 but I view it as unnecessary rn.

**Comment by mAAdhaTTah** [comment]
@RunDevelopment Yeah, I had a more involved idea that would allow us to ensure some consistency & reuse between the themes, but we definitely didn't decide on it.

@sivankanat If you're interested in pushing this, I'd be happy to discuss what the goals are and how we go about accomplishing them if you want to open an issue with more info. I'm going to close for now, but please feel free to pursue this if you have ideas for improving Prism!

**Comment by sivankanat** [comment]
@mAAdhaTTah
i think postcss, sass option is required in themes 
for more customization and simple integration in a npm install
is there any idea on this subject?

**Comment by mAAdhaTTah** [comment]
> i think postcss, sass option is required in themes
> for more customization and simple integration in a npm install

A consumer installing via `npm install` won't be using our build tools. If someone clones our repo, they can add whatever tools they want. Neither of these require us to change our implementation.

**Comment by sivankanat** [comment]
> > i think postcss, sass option is required in themes
> > for more customization and simple integration in a npm install
> 
> A consumer installing via `npm install` won't be using our build tools. If someone clones our repo, they can add whatever tools they want. Neither of these require us to change our implementation.

ok, thanks

**Pull request closed without merging**
