### PR TITLE
Drop support for NodeJS 10.x in development

### PR DESCRIPTION
**Pull request by RunDevelopment**
NodeJS 10.x lost support on [30 Apr 2021](https://endoflife.date/nodejs).

This PR removes NodeJS 10.x from your CI and changes the development requirements in the readme.

### CODE REVIEW

**Comment by mAAdhaTTah** [comment]
I feel like I said this when we dropped Node 8 support, but technically this is a breaking change.

**Comment by JaKXz** [comment]
On a related /tangential/hopefully not too controversial note, can I bring up the possibility of moving to ESM for v2.0 as well? We may already have an issue for this but I'm not sure 😅

**Comment by RunDevelopment** [comment]
> We may already have an issue for this

Yup, we do :) #2715. Moving to ESM is very much planned for v2.

**Comment by JaKXz** [comment]
@RunDevelopment is this already in the v2 branch? If not you could change the base branch to make the change easy :)

**Comment by RunDevelopment** [comment]
Yes, this is already implemented in v2. I'll close this now.

**Pull request closed without merging**
