### PR TITLE
Download all grammars as a Zip directly from the Autoloader plugin page

### PR DESCRIPTION
**Pull request by Golmote**
See #960 for details.

### CODE REVIEW

**Comment by zeitgeist87** [comment]
I've tested it in multiple browsers and it works really great! Amazing what you can do with JavaScript.

I've noticed one minor thing: You added `<script src="components.js"></script>` twice. Other than that it is ready to be merged.

**Comment by zeitgeist87** [comment]
We could also add all the third party libs to `package.json` and copy them over with `gulp`. For example add this to `package.json`:

```json
    "jszip": "^3.0.0",
    "file-saver": "^1.3.2"
```

and this to `gulp`:

```js
gulp.task('vendor', function () {
	return gulp.src([
			'./node_modules/jszip/dist/jszip.min.js',
			'./node_modules/file-saver/FileSaver.min.js'
		])
		.pipe(gulp.dest('vendor/'));
});
```

What do you think?

**Comment by Golmote** [comment]
> I've noticed one minor thing: You added `<script src="components.js"></script>` twice.

Woops! Nice catch.

> We could also add all the third party libs to `package.json` and copy them over with `gulp`.

We probably could. But we did not do it for es6-promises. Should we? I don't see the real benefits here.

**Comment by zeitgeist87** [comment]
> We probably could. But we did not do it for es6-promises. Should we? I don't see the real benefits here.

On the one hand, it would make it easier to keep these libs up to date. On the other hand, every second PR would probably contain changes to these files, because people don't know how to use git 😄.

You're right it's probably not a good idea.

**Comment by Golmote** [comment]
Anyway, we'll be able to change this anytime in the future if we feel the need ;). I'm merging.

**Pull request merged**
