### PR TITLE
Added fileHighlight function

### PR DESCRIPTION
**Pull request by hiulit**
This is what we were discussing on this issue https://github.com/PrismJS/prism/issues/390

I'm no JavaScript ninja so I don't even know if what I made is correct, but it works for me and it let's me call this function whenever I need it, so I can use it when loading dinamic content.

### CODE REVIEW

**Comment by Golmote** [comment]
I'd prefer if the variable was not declared globally. Using it as a property of the Prism object would be better IMO (`Prism.fileHighlight(...)`).

**Comment by hiulit** [comment]
I don't know if I feel capable to do the task... As I mentioned earlier, I'm no JavaScript ninja :P

If you think that would be useful, be my guest, or have someone else do it, for the sake of Prism! Hehe!

**Comment by Golmote** [comment]
What I'm asking for is in fact just a little change:

Instead of doing this:
```javascript
var fileHighlight = (function fileHighlight(){
    if (!self.Prism || !self.document || !document.querySelector) {
        return;
    }

    var Extensions = /* ...
        Plugin's code...
    ... */

    return fileHighlight;
}());
```

I'm suggesting you do this:
```javascript
(function () {
    if (!self.Prism || !self.document || !document.querySelector) {
        return;
    }

    // Declare it as a property of the Prism object
    self.Prism.fileHighlight = function() {

        var Extensions = /* ...
            Plugin's code...
        ... */

    };

    // Call it immediately
    self.Prism.fileHighlight();
}());
```

**Comment by LeaVerou** [comment]
Um, sorry for being thick, but what’s the purpose of this?

**Comment by Golmote** [comment]
It's all explained in issue #390. The purpose is to be able to call fileHighlight dynamically...

**Comment by hiulit** [comment]
Have I done it right? It's works for me.

**Comment by Golmote** [comment]
This looks good to me now ;) Thanks for refactoring it.

Now it's up to @LeaVerou to decide whether to merge it or not.

**Comment by LeaVerou** [comment]
Merged, thanks!

**Pull request merged**
